'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5446
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class ProjectStrings
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("AlarmMan.ProjectStrings", GetType(ProjectStrings).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend Shared ReadOnly Property CheckBox() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CheckBox", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Aborting.
        '''</summary>
        Friend Shared ReadOnly Property psABORTING() As String
            Get
                Return ResourceManager.GetString("psABORTING", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Alarm.
        '''</summary>
        Friend Shared ReadOnly Property psALARM_COL_CAP() As String
            Get
                Return ResourceManager.GetString("psALARM_COL_CAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Alarm Manager Started.
        '''</summary>
        Friend Shared ReadOnly Property psALARM_INT001() As String
            Get
                Return ResourceManager.GetString("psALARM_INT001", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Connection Established.
        '''</summary>
        Friend Shared ReadOnly Property psALARM_INT002() As String
            Get
                Return ResourceManager.GetString("psALARM_INT002", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Connection Lost.
        '''</summary>
        Friend Shared ReadOnly Property psALARM_INT003() As String
            Get
                Return ResourceManager.GetString("psALARM_INT003", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Connection Unavailable.
        '''</summary>
        Friend Shared ReadOnly Property psALARM_INT004() As String
            Get
                Return ResourceManager.GetString("psALARM_INT004", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to In Controlled Start.
        '''</summary>
        Friend Shared ReadOnly Property psALARM_INT005() As String
            Get
                Return ResourceManager.GetString("psALARM_INT005", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Network Connection Lost.
        '''</summary>
        Friend Shared ReadOnly Property psALARM_INT006() As String
            Get
                Return ResourceManager.GetString("psALARM_INT006", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Heartbeat Lost.
        '''</summary>
        Friend Shared ReadOnly Property psALARM_INT007() As String
            Get
                Return ResourceManager.GetString("psALARM_INT007", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ricko&apos;s Test alarm #99 --------------------------------.
        '''</summary>
        Friend Shared ReadOnly Property psALARM_INT099() As String
            Get
                Return ResourceManager.GetString("psALARM_INT099", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Alarm Mask Utility.
        '''</summary>
        Friend Shared ReadOnly Property psALARM_MASK_MNU() As String
            Get
                Return ResourceManager.GetString("psALARM_MASK_MNU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Show Alarm Mask configuration screen..
        '''</summary>
        Friend Shared ReadOnly Property psALARM_MASK_MNU_TT() As String
            Get
                Return ResourceManager.GetString("psALARM_MASK_MNU_TT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Auto Acknowledge.
        '''</summary>
        Friend Shared ReadOnly Property psAUTO_ACK_MNU() As String
            Get
                Return ResourceManager.GetString("psAUTO_ACK_MNU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Acknowledge and remove Reset alarms from the grid automatically..
        '''</summary>
        Friend Shared ReadOnly Property psAUTO_ACK_MNU_TT() As String
            Get
                Return ResourceManager.GetString("psAUTO_ACK_MNU_TT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Auto Refresh.
        '''</summary>
        Friend Shared ReadOnly Property psAUTO_REFR_MNU() As String
            Get
                Return ResourceManager.GetString("psAUTO_REFR_MNU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Automatically show new Alarms..
        '''</summary>
        Friend Shared ReadOnly Property psAUTO_REFR_MNU_TT() As String
            Get
                Return ResourceManager.GetString("psAUTO_REFR_MNU_TT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Automatic Refresh is OFF.
        '''</summary>
        Friend Shared ReadOnly Property psAUTO_REFRESH_OFF() As String
            Get
                Return ResourceManager.GetString("psAUTO_REFRESH_OFF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cause.
        '''</summary>
        Friend Shared ReadOnly Property psCAUSE_COL_CAP() As String
            Get
                Return ResourceManager.GetString("psCAUSE_COL_CAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Close this window..
        '''</summary>
        Friend Shared ReadOnly Property psCLOSE_TT() As String
            Get
                Return ResourceManager.GetString("psCLOSE_TT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Color.
        '''</summary>
        Friend Shared ReadOnly Property psCOLOR_COL_CAP() As String
            Get
                Return ResourceManager.GetString("psCOLOR_COL_CAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  Failed Initializing Works COM Object !.
        '''</summary>
        Friend Shared ReadOnly Property psCOM_INIT_FAIL_MSG() As String
            Get
                Return ResourceManager.GetString("psCOM_INIT_FAIL_MSG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Configuring PLC alarms.
        '''</summary>
        Friend Shared ReadOnly Property psCONFIG_PLC_ALARMS_MSG() As String
            Get
                Return ResourceManager.GetString("psCONFIG_PLC_ALARMS_MSG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Configuring Robot alarms.
        '''</summary>
        Friend Shared ReadOnly Property psCONFIG_ROB_ALARMS_MSG() As String
            Get
                Return ResourceManager.GetString("psCONFIG_ROB_ALARMS_MSG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Alarm manager establishing PLC connections..
        '''</summary>
        Friend Shared ReadOnly Property psCONN_PLC_MSG() As String
            Get
                Return ResourceManager.GetString("psCONN_PLC_MSG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Alarm manager establishing robot connections..
        '''</summary>
        Friend Shared ReadOnly Property psCONN_ROBOTS_MSG() As String
            Get
                Return ResourceManager.GetString("psCONN_ROBOTS_MSG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Default.
        '''</summary>
        Friend Shared ReadOnly Property psDEFAULT_MNU() As String
            Get
                Return ResourceManager.GetString("psDEFAULT_MNU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Show Default columns..
        '''</summary>
        Friend Shared ReadOnly Property psDEFAULT_MNU_TT() As String
            Get
                Return ResourceManager.GetString("psDEFAULT_MNU_TT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Description.
        '''</summary>
        Friend Shared ReadOnly Property psDESC_COL_CAP() As String
            Get
                Return ResourceManager.GetString("psDESC_COL_CAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Device.
        '''</summary>
        Friend Shared ReadOnly Property psDEVICE_COL_CAP() As String
            Get
                Return ResourceManager.GetString("psDEVICE_COL_CAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Filter Active.
        '''</summary>
        Friend Shared ReadOnly Property psFILTER_ACTIVE() As String
            Get
                Return ResourceManager.GetString("psFILTER_ACTIVE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to , Right-Click to Filter this column.
        '''</summary>
        Friend Shared ReadOnly Property psFILTER_TT() As String
            Get
                Return ResourceManager.GetString("psFILTER_TT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Full Help File.
        '''</summary>
        Friend Shared ReadOnly Property psFULL_FILE() As String
            Get
                Return ResourceManager.GetString("psFULL_FILE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Alarm Cause/Remedy Information.
        '''</summary>
        Friend Shared ReadOnly Property psHELP_FORM_CAP() As String
            Get
                Return ResourceManager.GetString("psHELP_FORM_CAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  Failed Initializing !.
        '''</summary>
        Friend Shared ReadOnly Property psINIT_FAIL_MSG() As String
            Get
                Return ResourceManager.GetString("psINIT_FAIL_MSG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Job ID.
        '''</summary>
        Friend Shared ReadOnly Property psJOB_ID_COL_CAP() As String
            Get
                Return ResourceManager.GetString("psJOB_ID_COL_CAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Job Name.
        '''</summary>
        Friend Shared ReadOnly Property psJOBNAME_COL_CAP() As String
            Get
                Return ResourceManager.GetString("psJOBNAME_COL_CAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Alarm Manager load error. See PAINTworks Event Log..
        '''</summary>
        Friend Shared ReadOnly Property psLOAD_ERROR() As String
            Get
                Return ResourceManager.GetString("psLOAD_ERROR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Alarm Manager.
        '''</summary>
        Friend Shared ReadOnly Property psMAIN_SCREEN_CAP() As String
            Get
                Return ResourceManager.GetString("psMAIN_SCREEN_CAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No Active Alarms.
        '''</summary>
        Friend Shared ReadOnly Property psNO_ALARMS() As String
            Get
                Return ResourceManager.GetString("psNO_ALARMS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Node.
        '''</summary>
        Friend Shared ReadOnly Property psNODE_COL_CAP() As String
            Get
                Return ResourceManager.GetString("psNODE_COL_CAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Options.
        '''</summary>
        Friend Shared ReadOnly Property psOPTIONS_MNU() As String
            Get
                Return ResourceManager.GetString("psOPTIONS_MNU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Show the Page Setup dialog..
        '''</summary>
        Friend Shared ReadOnly Property psPAGE_SETUP_MNU_TT() As String
            Get
                Return ResourceManager.GetString("psPAGE_SETUP_MNU_TT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save the document to an html file..
        '''</summary>
        Friend Shared ReadOnly Property psPRINT_FILE_MNU_TT() As String
            Get
                Return ResourceManager.GetString("psPRINT_FILE_MNU_TT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Show the Table Print Options dialog..
        '''</summary>
        Friend Shared ReadOnly Property psPRINT_OPTIONS_MNU_TT() As String
            Get
                Return ResourceManager.GetString("psPRINT_OPTIONS_MNU_TT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Preview the printed document..
        '''</summary>
        Friend Shared ReadOnly Property psPRINT_PREVIEW_MNU_TT() As String
            Get
                Return ResourceManager.GetString("psPRINT_PREVIEW_MNU_TT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Print Alarm Grid Contents..
        '''</summary>
        Friend Shared ReadOnly Property psPRINT_TT() As String
            Get
                Return ResourceManager.GetString("psPRINT_TT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Process.
        '''</summary>
        Friend Shared ReadOnly Property psPROCESS_COL_CAP() As String
            Get
                Return ResourceManager.GetString("psPROCESS_COL_CAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Production ID.
        '''</summary>
        Friend Shared ReadOnly Property psPROD_ID_COL_CAP() As String
            Get
                Return ResourceManager.GetString("psPROD_ID_COL_CAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Refresh.
        '''</summary>
        Friend Shared ReadOnly Property psREFRESH() As String
            Get
                Return ResourceManager.GetString("psREFRESH", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Refresh the Alarm grid..
        '''</summary>
        Friend Shared ReadOnly Property psREFRESH_TT() As String
            Get
                Return ResourceManager.GetString("psREFRESH_TT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Remove Filters.
        '''</summary>
        Friend Shared ReadOnly Property psREM_FILT_MNU() As String
            Get
                Return ResourceManager.GetString("psREM_FILT_MNU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Remove ALL column Filters..
        '''</summary>
        Friend Shared ReadOnly Property psREM_FILT_MNU_TT() As String
            Get
                Return ResourceManager.GetString("psREM_FILT_MNU_TT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Remove Sort.
        '''</summary>
        Friend Shared ReadOnly Property psREM_SORT_MNU() As String
            Get
                Return ResourceManager.GetString("psREM_SORT_MNU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Remove column Sort..
        '''</summary>
        Friend Shared ReadOnly Property psREM_SORT_MNU_TT() As String
            Get
                Return ResourceManager.GetString("psREM_SORT_MNU_TT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error: PLCAlarmStrings element not found.
        '''</summary>
        Friend Shared ReadOnly Property psRESOURCE_ERR() As String
            Get
                Return ResourceManager.GetString("psRESOURCE_ERR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save User column view settings operation failed..
        '''</summary>
        Friend Shared ReadOnly Property psSAVE_USER_FAIL() As String
            Get
                Return ResourceManager.GetString("psSAVE_USER_FAIL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save User View.
        '''</summary>
        Friend Shared ReadOnly Property psSAVE_USER_MNU() As String
            Get
                Return ResourceManager.GetString("psSAVE_USER_MNU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save User column view settings..
        '''</summary>
        Friend Shared ReadOnly Property psSAVE_USER_MNU_TT() As String
            Get
                Return ResourceManager.GetString("psSAVE_USER_MNU_TT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save User column view settings operation success!.
        '''</summary>
        Friend Shared ReadOnly Property psSAVE_USER_SUCCESS() As String
            Get
                Return ResourceManager.GetString("psSAVE_USER_SUCCESS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Active Alarms.
        '''</summary>
        Friend Shared ReadOnly Property psSCREENCAPTION() As String
            Get
                Return ResourceManager.GetString("psSCREENCAPTION", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select Printer.
        '''</summary>
        Friend Shared ReadOnly Property psSEL_PRINTER_MNU() As String
            Get
                Return ResourceManager.GetString("psSEL_PRINTER_MNU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select destination printer..
        '''</summary>
        Friend Shared ReadOnly Property psSEL_PRINTER_MNU_TT() As String
            Get
                Return ResourceManager.GetString("psSEL_PRINTER_MNU_TT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Severity.
        '''</summary>
        Friend Shared ReadOnly Property psSEVERITY_COL_CAP() As String
            Get
                Return ResourceManager.GetString("psSEVERITY_COL_CAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to One Alarm .
        '''</summary>
        Friend Shared ReadOnly Property psSINGLE_ALARM() As String
            Get
                Return ResourceManager.GetString("psSINGLE_ALARM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Left-Click to Sort this column.
        '''</summary>
        Friend Shared ReadOnly Property psSORT_TT() As String
            Get
                Return ResourceManager.GetString("psSORT_TT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Start Time.
        '''</summary>
        Friend Shared ReadOnly Property psSTART_COL_CAP() As String
            Get
                Return ResourceManager.GetString("psSTART_COL_CAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Status.
        '''</summary>
        Friend Shared ReadOnly Property psSTATUS_COL_CAP() As String
            Get
                Return ResourceManager.GetString("psSTATUS_COL_CAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Style.
        '''</summary>
        Friend Shared ReadOnly Property psSTYLE_COL_CAP() As String
            Get
                Return ResourceManager.GetString("psSTYLE_COL_CAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Updating ....
        '''</summary>
        Friend Shared ReadOnly Property psUPDATING() As String
            Get
                Return ResourceManager.GetString("psUPDATING", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to User.
        '''</summary>
        Friend Shared ReadOnly Property psUSER_MNU() As String
            Get
                Return ResourceManager.GetString("psUSER_MNU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Show User selected columns..
        '''</summary>
        Friend Shared ReadOnly Property psUSER_MNU_TT() As String
            Get
                Return ResourceManager.GetString("psUSER_MNU_TT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Valve.
        '''</summary>
        Friend Shared ReadOnly Property psVALVE_COL_CAP() As String
            Get
                Return ResourceManager.GetString("psVALVE_COL_CAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to View.
        '''</summary>
        Friend Shared ReadOnly Property psVIEW() As String
            Get
                Return ResourceManager.GetString("psVIEW", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Change View settings..
        '''</summary>
        Friend Shared ReadOnly Property psVIEW_TT() As String
            Get
                Return ResourceManager.GetString("psVIEW_TT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Zone.
        '''</summary>
        Friend Shared ReadOnly Property psZONE_COL_CAP() As String
            Get
                Return ResourceManager.GetString("psZONE_COL_CAP", resourceCulture)
            End Get
        End Property
        
        Friend Shared ReadOnly Property REDBELL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("REDBELL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Class
End Namespace
