'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5485
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'This class was auto-generated by the StronglyTypedResourceBuilder
'class via a tool like ResGen or Visual Studio.
'To add or remove a member, edit your .ResX file then rerun ResGen
'with the /str option, or rebuild your VS project.
'''<summary>
'''  A strongly-typed resource class, for looking up localized strings, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Friend Class Devices
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Returns the cached ResourceManager instance used by this class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("FluidMaint.Devices", GetType(Devices).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Overrides the current thread's CurrentUICulture property for all
    '''  resource lookups using this strongly typed resource class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Device Status For Manual Functions.
    '''</summary>
    Friend Shared ReadOnly Property dsDeviceScreen() As String
        Get
            Return ResourceManager.GetString("dsDeviceScreen", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Robot Not Running.
    '''</summary>
    Friend Shared ReadOnly Property dsRobotOff01() As String
        Get
            Return ResourceManager.GetString("dsRobotOff01", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Robot Not Selected.
    '''</summary>
    Friend Shared ReadOnly Property dsRobotOff02() As String
        Get
            Return ResourceManager.GetString("dsRobotOff02", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Applicator Not Enabled.
    '''</summary>
    Friend Shared ReadOnly Property dsRobotOff03() As String
        Get
            Return ResourceManager.GetString("dsRobotOff03", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Color Change Cycle Active.
    '''</summary>
    Friend Shared ReadOnly Property dsRobotOff04() As String
        Get
            Return ResourceManager.GetString("dsRobotOff04", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to .
    '''</summary>
    Friend Shared ReadOnly Property dsRobotOff05() As String
        Get
            Return ResourceManager.GetString("dsRobotOff05", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Manual Enable Not Active.
    '''</summary>
    Friend Shared ReadOnly Property dsRobotOff06() As String
        Get
            Return ResourceManager.GetString("dsRobotOff06", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Teach Pendant Enabled.
    '''</summary>
    Friend Shared ReadOnly Property dsRobotOff07() As String
        Get
            Return ResourceManager.GetString("dsRobotOff07", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Not at Home.
    '''</summary>
    Friend Shared ReadOnly Property dsRobotOff08() As String
        Get
            Return ResourceManager.GetString("dsRobotOff08", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Robot Running.
    '''</summary>
    Friend Shared ReadOnly Property dsRobotOn01() As String
        Get
            Return ResourceManager.GetString("dsRobotOn01", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Robot Selected.
    '''</summary>
    Friend Shared ReadOnly Property dsRobotOn02() As String
        Get
            Return ResourceManager.GetString("dsRobotOn02", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Applicator Enabled.
    '''</summary>
    Friend Shared ReadOnly Property dsRobotOn03() As String
        Get
            Return ResourceManager.GetString("dsRobotOn03", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Color Change Cycle Not Active.
    '''</summary>
    Friend Shared ReadOnly Property dsRobotOn04() As String
        Get
            Return ResourceManager.GetString("dsRobotOn04", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to .
    '''</summary>
    Friend Shared ReadOnly Property dsRobotOn05() As String
        Get
            Return ResourceManager.GetString("dsRobotOn05", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Manual Enable Active.
    '''</summary>
    Friend Shared ReadOnly Property dsRobotOn06() As String
        Get
            Return ResourceManager.GetString("dsRobotOn06", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Teach Pendant Disabled.
    '''</summary>
    Friend Shared ReadOnly Property dsRobotOn07() As String
        Get
            Return ResourceManager.GetString("dsRobotOn07", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to At Home.
    '''</summary>
    Friend Shared ReadOnly Property dsRobotOn08() As String
        Get
            Return ResourceManager.GetString("dsRobotOn08", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Not In Manual Mode.
    '''</summary>
    Friend Shared ReadOnly Property dsZoneOff01() As String
        Get
            Return ResourceManager.GetString("dsZoneOff01", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Booth Air Not OK.
    '''</summary>
    Friend Shared ReadOnly Property dsZoneOff02() As String
        Get
            Return ResourceManager.GetString("dsZoneOff02", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Intrusion Not OK.
    '''</summary>
    Friend Shared ReadOnly Property dsZoneOff03() As String
        Get
            Return ResourceManager.GetString("dsZoneOff03", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Estop PB Active.
    '''</summary>
    Friend Shared ReadOnly Property dsZoneOff04() As String
        Get
            Return ResourceManager.GetString("dsZoneOff04", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Master Power Off.
    '''</summary>
    Friend Shared ReadOnly Property dsZoneOff05() As String
        Get
            Return ResourceManager.GetString("dsZoneOff05", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Fire Interlock Not OK.
    '''</summary>
    Friend Shared ReadOnly Property dsZoneOff06() As String
        Get
            Return ResourceManager.GetString("dsZoneOff06", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to .
    '''</summary>
    Friend Shared ReadOnly Property dsZoneOff07() As String
        Get
            Return ResourceManager.GetString("dsZoneOff07", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to .
    '''</summary>
    Friend Shared ReadOnly Property dsZoneOff08() As String
        Get
            Return ResourceManager.GetString("dsZoneOff08", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Manual Mode Active.
    '''</summary>
    Friend Shared ReadOnly Property dsZoneOn01() As String
        Get
            Return ResourceManager.GetString("dsZoneOn01", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Booth Air OK.
    '''</summary>
    Friend Shared ReadOnly Property dsZoneOn02() As String
        Get
            Return ResourceManager.GetString("dsZoneOn02", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Intrusion OK.
    '''</summary>
    Friend Shared ReadOnly Property dsZoneOn03() As String
        Get
            Return ResourceManager.GetString("dsZoneOn03", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Estop PB&apos;s OK.
    '''</summary>
    Friend Shared ReadOnly Property dsZoneOn04() As String
        Get
            Return ResourceManager.GetString("dsZoneOn04", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Master Power On.
    '''</summary>
    Friend Shared ReadOnly Property dsZoneOn05() As String
        Get
            Return ResourceManager.GetString("dsZoneOn05", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Fire Interlock OK.
    '''</summary>
    Friend Shared ReadOnly Property dsZoneOn06() As String
        Get
            Return ResourceManager.GetString("dsZoneOn06", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to .
    '''</summary>
    Friend Shared ReadOnly Property dsZoneOn07() As String
        Get
            Return ResourceManager.GetString("dsZoneOn07", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to  .
    '''</summary>
    Friend Shared ReadOnly Property dsZoneOn08() As String
        Get
            Return ResourceManager.GetString("dsZoneOn08", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Zone.
    '''</summary>
    Friend Shared ReadOnly Property dsZoneTitle() As String
        Get
            Return ResourceManager.GetString("dsZoneTitle", resourceCulture)
        End Get
    End Property
End Class
