'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4961
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class ProjectStrings
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Network.ProjectStrings", GetType(ProjectStrings).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend Shared ReadOnly Property FormIcon() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("FormIcon", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Arp.
        '''</summary>
        Friend Shared ReadOnly Property psARP() As String
            Get
                Return ResourceManager.GetString("psARP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Auto Configure.
        '''</summary>
        Friend Shared ReadOnly Property psAUTO_CFG() As String
            Get
                Return ResourceManager.GetString("psAUTO_CFG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This will fill in the configuration for the BOOTP server.  The changes will not be saved automatically.  Review the output before saving..
        '''</summary>
        Friend Shared ReadOnly Property psAUTO_CFG_BOOTP_PROMPT1() As String
            Get
                Return ResourceManager.GetString("psAUTO_CFG_BOOTP_PROMPT1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Auto Configure BOOTP.
        '''</summary>
        Friend Shared ReadOnly Property psAUTO_CFG_BOOTP_PROMPT2() As String
            Get
                Return ResourceManager.GetString("psAUTO_CFG_BOOTP_PROMPT2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This will fill in the configuration for the TFTP server.  The changes will not be saved automatically.  Review the output before saving..
        '''</summary>
        Friend Shared ReadOnly Property psAUTO_CFG_TFTP_PROMPT1() As String
            Get
                Return ResourceManager.GetString("psAUTO_CFG_TFTP_PROMPT1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Auto Configure TFTP.
        '''</summary>
        Friend Shared ReadOnly Property psAUTO_CFG_TFTP_PROMPT2() As String
            Get
                Return ResourceManager.GetString("psAUTO_CFG_TFTP_PROMPT2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bootp Setup.
        '''</summary>
        Friend Shared ReadOnly Property psBOOTP_CFG() As String
            Get
                Return ResourceManager.GetString("psBOOTP_CFG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Start BOOTP.
        '''</summary>
        Friend Shared ReadOnly Property psBOOTP_START() As String
            Get
                Return ResourceManager.GetString("psBOOTP_START", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to BOOTP Status.
        '''</summary>
        Friend Shared ReadOnly Property psBOOTP_STATUS() As String
            Get
                Return ResourceManager.GetString("psBOOTP_STATUS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stop BOOTP.
        '''</summary>
        Friend Shared ReadOnly Property psBOOTP_STOP() As String
            Get
                Return ResourceManager.GetString("psBOOTP_STOP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Clear output window.
        '''</summary>
        Friend Shared ReadOnly Property psCLEAR_OUTPUT_WINDOW() As String
            Get
                Return ResourceManager.GetString("psCLEAR_OUTPUT_WINDOW", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Clear Result Window?.
        '''</summary>
        Friend Shared ReadOnly Property psCLEAR_WINDOW_QUES() As String
            Get
                Return ResourceManager.GetString("psCLEAR_WINDOW_QUES", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Controllers.
        '''</summary>
        Friend Shared ReadOnly Property psCONTROLLERS() As String
            Get
                Return ResourceManager.GetString("psCONTROLLERS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Copy to clipboard.
        '''</summary>
        Friend Shared ReadOnly Property psCOPY_TO_CLIPBOARD() As String
            Get
                Return ResourceManager.GetString("psCOPY_TO_CLIPBOARD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cut to clipboard.
        '''</summary>
        Friend Shared ReadOnly Property psCUT_TO_CLIPBOARD() As String
            Get
                Return ResourceManager.GetString("psCUT_TO_CLIPBOARD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Update BOOTP.
        '''</summary>
        Friend Shared ReadOnly Property psECBR_UPDATE() As String
            Get
                Return ResourceManager.GetString("psECBR_UPDATE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Update BOOTP &amp; TFTP server configuration..
        '''</summary>
        Friend Shared ReadOnly Property psECBR_UPDATE_SVR_CFG() As String
            Get
                Return ResourceManager.GetString("psECBR_UPDATE_SVR_CFG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Failed to run command.
        '''</summary>
        Friend Shared ReadOnly Property psFAILED_TO_RUN() As String
            Get
                Return ResourceManager.GetString("psFAILED_TO_RUN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Controller Fanuc Name: .
        '''</summary>
        Friend Shared ReadOnly Property psFANUC_NAME() As String
            Get
                Return ResourceManager.GetString("psFANUC_NAME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fanuc Ping.
        '''</summary>
        Friend Shared ReadOnly Property psFANUC_PING() As String
            Get
                Return ResourceManager.GetString("psFANUC_PING", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fanuc Ping Failed.
        '''</summary>
        Friend Shared ReadOnly Property psFANUC_PING_FAILED() As String
            Get
                Return ResourceManager.GetString("psFANUC_PING_FAILED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fanuc Ping Successful.
        '''</summary>
        Friend Shared ReadOnly Property psFANUC_PING_OK() As String
            Get
                Return ResourceManager.GetString("psFANUC_PING_OK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Host Names File.
        '''</summary>
        Friend Shared ReadOnly Property psHOST_FILE() As String
            Get
                Return ResourceManager.GetString("psHOST_FILE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Host File Items.
        '''</summary>
        Friend Shared ReadOnly Property psHOSTFILEITEMS() As String
            Get
                Return ResourceManager.GetString("psHOSTFILEITEMS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Controller IPAddress: .
        '''</summary>
        Friend Shared ReadOnly Property psIP_ADDRESS() As String
            Get
                Return ResourceManager.GetString("psIP_ADDRESS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to IP Config.
        '''</summary>
        Friend Shared ReadOnly Property psIP_CONFIG() As String
            Get
                Return ResourceManager.GetString("psIP_CONFIG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Manual Address.
        '''</summary>
        Friend Shared ReadOnly Property psMANUAL_ADDRESS() As String
            Get
                Return ResourceManager.GetString("psMANUAL_ADDRESS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Controller Name: .
        '''</summary>
        Friend Shared ReadOnly Property psNAME() As String
            Get
                Return ResourceManager.GetString("psNAME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Output Window.
        '''</summary>
        Friend Shared ReadOnly Property psOUTPUT_WINDOW() As String
            Get
                Return ResourceManager.GetString("psOUTPUT_WINDOW", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Paste from clipboard.
        '''</summary>
        Friend Shared ReadOnly Property psPASTE_FROM_CLIPBOARD() As String
            Get
                Return ResourceManager.GetString("psPASTE_FROM_CLIPBOARD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Performing Fanuc Ping On .
        '''</summary>
        Friend Shared ReadOnly Property psPERF_FANUC_PING_ON() As String
            Get
                Return ResourceManager.GetString("psPERF_FANUC_PING_ON", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ping.
        '''</summary>
        Friend Shared ReadOnly Property psPING() As String
            Get
                Return ResourceManager.GetString("psPING", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Print document.
        '''</summary>
        Friend Shared ReadOnly Property psPRINT_DOCUMENT() As String
            Get
                Return ResourceManager.GetString("psPRINT_DOCUMENT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save document.
        '''</summary>
        Friend Shared ReadOnly Property psSAVE_DOCUMENT() As String
            Get
                Return ResourceManager.GetString("psSAVE_DOCUMENT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Saved .
        '''</summary>
        Friend Shared ReadOnly Property psSAVED_() As String
            Get
                Return ResourceManager.GetString("psSAVED_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Saved hosts file to .
        '''</summary>
        Friend Shared ReadOnly Property psSAVED_HOSTS() As String
            Get
                Return ResourceManager.GetString("psSAVED_HOSTS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Saved output file to .
        '''</summary>
        Friend Shared ReadOnly Property psSAVED_OUTPUT() As String
            Get
                Return ResourceManager.GetString("psSAVED_OUTPUT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Network Maintenance.
        '''</summary>
        Friend Shared ReadOnly Property psSCREENCAPTION() As String
            Get
                Return ResourceManager.GetString("psSCREENCAPTION", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to TFTP Setup.
        '''</summary>
        Friend Shared ReadOnly Property psTFTP_CFG() As String
            Get
                Return ResourceManager.GetString("psTFTP_CFG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Start TFTP.
        '''</summary>
        Friend Shared ReadOnly Property psTFTP_START() As String
            Get
                Return ResourceManager.GetString("psTFTP_START", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to TFTP Status.
        '''</summary>
        Friend Shared ReadOnly Property psTFTP_STATUS() As String
            Get
                Return ResourceManager.GetString("psTFTP_STATUS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stop TFTP.
        '''</summary>
        Friend Shared ReadOnly Property psTFTP_STOP() As String
            Get
                Return ResourceManager.GetString("psTFTP_STOP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Traceroute.
        '''</summary>
        Friend Shared ReadOnly Property psTRACE_ROUTE() As String
            Get
                Return ResourceManager.GetString("psTRACE_ROUTE", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
