'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4963
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class ProjectStrings
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Robot_IO.ProjectStrings", GetType(ProjectStrings).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend Shared ReadOnly Property FormIcon() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("FormIcon", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend Shared ReadOnly Property LIGHTOFF() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LIGHTOFF", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property LIGHTON() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LIGHTON", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to AI: Analog Inputs.
        '''</summary>
        Friend Shared ReadOnly Property psAI() As String
            Get
                Return ResourceManager.GetString("psAI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to AI[{0}:{1}].
        '''</summary>
        Friend Shared ReadOnly Property psAI_CMT() As String
            Get
                Return ResourceManager.GetString("psAI_CMT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to AO: Analog Outputs.
        '''</summary>
        Friend Shared ReadOnly Property psAO() As String
            Get
                Return ResourceManager.GetString("psAO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to AO[{0}:{1}].
        '''</summary>
        Friend Shared ReadOnly Property psAO_CMT() As String
            Get
                Return ResourceManager.GetString("psAO_CMT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to AutoRefresh.
        '''</summary>
        Friend Shared ReadOnly Property psAUTOREFRESH() As String
            Get
                Return ResourceManager.GetString("psAUTOREFRESH", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Set I/O comment for .
        '''</summary>
        Friend Shared ReadOnly Property psCL_SET_CMT() As String
            Get
                Return ResourceManager.GetString("psCL_SET_CMT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Set I/O simulate for.
        '''</summary>
        Friend Shared ReadOnly Property psCL_SET_SIM() As String
            Get
                Return ResourceManager.GetString("psCL_SET_SIM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Set I/O value for.
        '''</summary>
        Friend Shared ReadOnly Property psCL_SET_VAL() As String
            Get
                Return ResourceManager.GetString("psCL_SET_VAL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unsimulate all I/O.
        '''</summary>
        Friend Shared ReadOnly Property psCL_UNSIMALL() As String
            Get
                Return ResourceManager.GetString("psCL_UNSIMALL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Label.
        '''</summary>
        Friend Shared ReadOnly Property psCOL_LABEL() As String
            Get
                Return ResourceManager.GetString("psCOL_LABEL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sim.
        '''</summary>
        Friend Shared ReadOnly Property psCOL_SIM() As String
            Get
                Return ResourceManager.GetString("psCOL_SIM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Value.
        '''</summary>
        Friend Shared ReadOnly Property psCOL_VALUE() As String
            Get
                Return ResourceManager.GetString("psCOL_VALUE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DI: Digital Inputs.
        '''</summary>
        Friend Shared ReadOnly Property psDI() As String
            Get
                Return ResourceManager.GetString("psDI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DI[{0}:{1}].
        '''</summary>
        Friend Shared ReadOnly Property psDI_CMT() As String
            Get
                Return ResourceManager.GetString("psDI_CMT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Set the new I/O Comment.  Changes will be written to the robot immediately..
        '''</summary>
        Friend Shared ReadOnly Property psDLG_CMT_LABEL() As String
            Get
                Return ResourceManager.GetString("psDLG_CMT_LABEL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Set I/O Comment.
        '''</summary>
        Friend Shared ReadOnly Property psDLG_CMT_TITLE() As String
            Get
                Return ResourceManager.GetString("psDLG_CMT_TITLE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select the auto-refresh rate in milliseconds..
        '''</summary>
        Friend Shared ReadOnly Property psDLG_REF_LABEL() As String
            Get
                Return ResourceManager.GetString("psDLG_REF_LABEL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Refresh Rate.
        '''</summary>
        Friend Shared ReadOnly Property psDLG_REF_TITLE() As String
            Get
                Return ResourceManager.GetString("psDLG_REF_TITLE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DO: Digital Outputs.
        '''</summary>
        Friend Shared ReadOnly Property psDO() As String
            Get
                Return ResourceManager.GetString("psDO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DO[{0}:{1}].
        '''</summary>
        Friend Shared ReadOnly Property psDO_CMT() As String
            Get
                Return ResourceManager.GetString("psDO_CMT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to End All Monitors.
        '''</summary>
        Friend Shared ReadOnly Property psEND_ALL_MON() As String
            Get
                Return ResourceManager.GetString("psEND_ALL_MON", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to End Monitor.
        '''</summary>
        Friend Shared ReadOnly Property psEND_MON() As String
            Get
                Return ResourceManager.GetString("psEND_MON", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to F: Flag .
        '''</summary>
        Friend Shared ReadOnly Property psFL() As String
            Get
                Return ResourceManager.GetString("psFL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to F[{0}:{1}].
        '''</summary>
        Friend Shared ReadOnly Property psFL_CMT() As String
            Get
                Return ResourceManager.GetString("psFL_CMT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to GI: Group Inputs.
        '''</summary>
        Friend Shared ReadOnly Property psGI() As String
            Get
                Return ResourceManager.GetString("psGI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to GI[{0}:{1}].
        '''</summary>
        Friend Shared ReadOnly Property psGI_CMT() As String
            Get
                Return ResourceManager.GetString("psGI_CMT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to GO: Group Outputs.
        '''</summary>
        Friend Shared ReadOnly Property psGO() As String
            Get
                Return ResourceManager.GetString("psGO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to GO[{0}:{1}].
        '''</summary>
        Friend Shared ReadOnly Property psGO_CMT() As String
            Get
                Return ResourceManager.GetString("psGO_CMT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid Value.
        '''</summary>
        Friend Shared ReadOnly Property psINV_BOOL_CAP() As String
            Get
                Return ResourceManager.GetString("psINV_BOOL_CAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid Boolean value..
        '''</summary>
        Friend Shared ReadOnly Property psINV_BOOL_TEXT() As String
            Get
                Return ResourceManager.GetString("psINV_BOOL_TEXT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid Value.
        '''</summary>
        Friend Shared ReadOnly Property psINV_INT_CAP() As String
            Get
                Return ResourceManager.GetString("psINV_INT_CAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid Integer value..
        '''</summary>
        Friend Shared ReadOnly Property psINV_INT_TEXT() As String
            Get
                Return ResourceManager.GetString("psINV_INT_TEXT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to IOType:.
        '''</summary>
        Friend Shared ReadOnly Property psIOTYPE() As String
            Get
                Return ResourceManager.GetString("psIOTYPE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to M: Marker.
        '''</summary>
        Friend Shared ReadOnly Property psMARKER() As String
            Get
                Return ResourceManager.GetString("psMARKER", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to M[{0}:{1}].
        '''</summary>
        Friend Shared ReadOnly Property psMARKER_CMT() As String
            Get
                Return ResourceManager.GetString("psMARKER_CMT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Add Monitor.
        '''</summary>
        Friend Shared ReadOnly Property psMONITOR() As String
            Get
                Return ResourceManager.GetString("psMONITOR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ms.
        '''</summary>
        Friend Shared ReadOnly Property psMS() As String
            Get
                Return ResourceManager.GetString("psMS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to N/A.
        '''</summary>
        Friend Shared ReadOnly Property psNA() As String
            Get
                Return ResourceManager.GetString("psNA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to OFF.
        '''</summary>
        Friend Shared ReadOnly Property psOFF() As String
            Get
                Return ResourceManager.GetString("psOFF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ON.
        '''</summary>
        Friend Shared ReadOnly Property psON() As String
            Get
                Return ResourceManager.GetString("psON", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PI: PLC Inputs.
        '''</summary>
        Friend Shared ReadOnly Property psPLCI() As String
            Get
                Return ResourceManager.GetString("psPLCI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PI[{0}:{1}].
        '''</summary>
        Friend Shared ReadOnly Property psPLCI_CMT() As String
            Get
                Return ResourceManager.GetString("psPLCI_CMT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PO: PLC Outputs.
        '''</summary>
        Friend Shared ReadOnly Property psPLCO() As String
            Get
                Return ResourceManager.GetString("psPLCO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PO[{0}:{1}].
        '''</summary>
        Friend Shared ReadOnly Property psPLCO_CMT() As String
            Get
                Return ResourceManager.GetString("psPLCO_CMT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to RI: Robot Inputs.
        '''</summary>
        Friend Shared ReadOnly Property psRI() As String
            Get
                Return ResourceManager.GetString("psRI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to RI[{0}:{1}].
        '''</summary>
        Friend Shared ReadOnly Property psRI_CMT() As String
            Get
                Return ResourceManager.GetString("psRI_CMT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to RO: Robot Outputs.
        '''</summary>
        Friend Shared ReadOnly Property psRO() As String
            Get
                Return ResourceManager.GetString("psRO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to RO[{0}:{1}].
        '''</summary>
        Friend Shared ReadOnly Property psRO_CMT() As String
            Get
                Return ResourceManager.GetString("psRO_CMT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Robot IO.
        '''</summary>
        Friend Shared ReadOnly Property psSCREENCAPTION() As String
            Get
                Return ResourceManager.GetString("psSCREENCAPTION", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Set.
        '''</summary>
        Friend Shared ReadOnly Property psSET() As String
            Get
                Return ResourceManager.GetString("psSET", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error.
        '''</summary>
        Friend Shared ReadOnly Property psSET_CMT_FAIL_CAP() As String
            Get
                Return ResourceManager.GetString("psSET_CMT_FAIL_CAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Failed to set I/O comment..
        '''</summary>
        Friend Shared ReadOnly Property psSET_CMT_FAIL_TEXT() As String
            Get
                Return ResourceManager.GetString("psSET_CMT_FAIL_TEXT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error.
        '''</summary>
        Friend Shared ReadOnly Property psSET_FAILED_CAP() As String
            Get
                Return ResourceManager.GetString("psSET_FAILED_CAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Failed to set I/O Value.
        '''</summary>
        Friend Shared ReadOnly Property psSET_FAILED_TEXT() As String
            Get
                Return ResourceManager.GetString("psSET_FAILED_TEXT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error.
        '''</summary>
        Friend Shared ReadOnly Property psSET_SIM_FAILED_CAP() As String
            Get
                Return ResourceManager.GetString("psSET_SIM_FAILED_CAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Failed to set simulate status.
        '''</summary>
        Friend Shared ReadOnly Property psSET_SIM_FAILED_TEXT() As String
            Get
                Return ResourceManager.GetString("psSET_SIM_FAILED_TEXT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Set I/O Value.
        '''</summary>
        Friend Shared ReadOnly Property psSET_WARN_CAP() As String
            Get
                Return ResourceManager.GetString("psSET_WARN_CAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Warning: I/O change will be written to the robot immediately..
        '''</summary>
        Friend Shared ReadOnly Property psSET_WARN_TXT() As String
            Get
                Return ResourceManager.GetString("psSET_WARN_TXT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Set Comment.
        '''</summary>
        Friend Shared ReadOnly Property psSETCOMMENT() As String
            Get
                Return ResourceManager.GetString("psSETCOMMENT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SI: SOP Inputs.
        '''</summary>
        Friend Shared ReadOnly Property psSI() As String
            Get
                Return ResourceManager.GetString("psSI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SI[{0}:{1}].
        '''</summary>
        Friend Shared ReadOnly Property psSI_CMT() As String
            Get
                Return ResourceManager.GetString("psSI_CMT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SIM: .
        '''</summary>
        Friend Shared ReadOnly Property psSIM() As String
            Get
                Return ResourceManager.GetString("psSIM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Simulate.
        '''</summary>
        Friend Shared ReadOnly Property psSIM_WARN_CAP() As String
            Get
                Return ResourceManager.GetString("psSIM_WARN_CAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Warning: Simulate change will be written to the robot immediately..
        '''</summary>
        Friend Shared ReadOnly Property psSIM_WARN_TXT() As String
            Get
                Return ResourceManager.GetString("psSIM_WARN_TXT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Simulate.
        '''</summary>
        Friend Shared ReadOnly Property psSIMULATE() As String
            Get
                Return ResourceManager.GetString("psSIMULATE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SO: SOP Outputs.
        '''</summary>
        Friend Shared ReadOnly Property psSO() As String
            Get
                Return ResourceManager.GetString("psSO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SO[{0}:{1}].
        '''</summary>
        Friend Shared ReadOnly Property psSO_CMT() As String
            Get
                Return ResourceManager.GetString("psSO_CMT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to TPI: TP Inputs.
        '''</summary>
        Friend Shared ReadOnly Property psTPI() As String
            Get
                Return ResourceManager.GetString("psTPI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to TPI[{0}:{1}].
        '''</summary>
        Friend Shared ReadOnly Property psTPI_CMT() As String
            Get
                Return ResourceManager.GetString("psTPI_CMT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to TPO: TP Outputs.
        '''</summary>
        Friend Shared ReadOnly Property psTPO() As String
            Get
                Return ResourceManager.GetString("psTPO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to TPO[{0}:{1}].
        '''</summary>
        Friend Shared ReadOnly Property psTPO_CMT() As String
            Get
                Return ResourceManager.GetString("psTPO_CMT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UI: UOP Inputs.
        '''</summary>
        Friend Shared ReadOnly Property psUI() As String
            Get
                Return ResourceManager.GetString("psUI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UI[{0}:{1}].
        '''</summary>
        Friend Shared ReadOnly Property psUI_CMT() As String
            Get
                Return ResourceManager.GetString("psUI_CMT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unsimulate All.
        '''</summary>
        Friend Shared ReadOnly Property psUNSIMALL() As String
            Get
                Return ResourceManager.GetString("psUNSIMALL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unsimulate.
        '''</summary>
        Friend Shared ReadOnly Property psUNSIMULATE() As String
            Get
                Return ResourceManager.GetString("psUNSIMULATE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UO: UOP Outputs.
        '''</summary>
        Friend Shared ReadOnly Property psUO() As String
            Get
                Return ResourceManager.GetString("psUO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UO[{0}:{1}].
        '''</summary>
        Friend Shared ReadOnly Property psUO_CMT() As String
            Get
                Return ResourceManager.GetString("psUO_CMT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to WI: Weld Inputs.
        '''</summary>
        Friend Shared ReadOnly Property psWI() As String
            Get
                Return ResourceManager.GetString("psWI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to WO: Weld Outputs.
        '''</summary>
        Friend Shared ReadOnly Property psWO() As String
            Get
                Return ResourceManager.GetString("psWO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to WO[{0}:{1}].
        '''</summary>
        Friend Shared ReadOnly Property psWO_CMT() As String
            Get
                Return ResourceManager.GetString("psWO_CMT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to WI[{0}:{1}].
        '''</summary>
        Friend Shared ReadOnly Property pWI_CMT() As String
            Get
                Return ResourceManager.GetString("pWI_CMT", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
