'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3615
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class ProjectStrings
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("RobotVariables.ProjectStrings", GetType(ProjectStrings).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend Shared ReadOnly Property FormIcon() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("FormIcon", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Accept.
        '''</summary>
        Friend Shared ReadOnly Property psACCEPT() As String
            Get
                Return ResourceManager.GetString("psACCEPT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Application.
        '''</summary>
        Friend Shared ReadOnly Property psACCESS_APP() As String
            Get
                Return ResourceManager.GetString("psACCESS_APP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Access:.
        '''</summary>
        Friend Shared ReadOnly Property psACCESS_CAP() As String
            Get
                Return ResourceManager.GetString("psACCESS_CAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Field Protection.
        '''</summary>
        Friend Shared ReadOnly Property psACCESS_FP() As String
            Get
                Return ResourceManager.GetString("psACCESS_FP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Motion Control.
        '''</summary>
        Friend Shared ReadOnly Property psACCESS_MOT() As String
            Get
                Return ResourceManager.GetString("psACCESS_MOT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No Access.
        '''</summary>
        Friend Shared ReadOnly Property psACCESS_NO() As String
            Get
                Return ResourceManager.GetString("psACCESS_NO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Read Access.
        '''</summary>
        Friend Shared ReadOnly Property psACCESS_RD() As String
            Get
                Return ResourceManager.GetString("psACCESS_RD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Read/Write.
        '''</summary>
        Friend Shared ReadOnly Property psACCESS_RW() As String
            Get
                Return ResourceManager.GetString("psACCESS_RW", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Add.
        '''</summary>
        Friend Shared ReadOnly Property psADD() As String
            Get
                Return ResourceManager.GetString("psADD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  already exists in the list..
        '''</summary>
        Friend Shared ReadOnly Property psALREADY_EXISTS() As String
            Get
                Return ResourceManager.GetString("psALREADY_EXISTS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Already In List..
        '''</summary>
        Friend Shared ReadOnly Property psALREADY_IN_LIST() As String
            Get
                Return ResourceManager.GetString("psALREADY_IN_LIST", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Browse.
        '''</summary>
        Friend Shared ReadOnly Property psBROWSE() As String
            Get
                Return ResourceManager.GetString("psBROWSE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cannot write position data..
        '''</summary>
        Friend Shared ReadOnly Property psCANNOT_WRITE_POS_DAT() As String
            Get
                Return ResourceManager.GetString("psCANNOT_WRITE_POS_DAT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cannot wite to variable: .
        '''</summary>
        Friend Shared ReadOnly Property psCANNOT_WRITE_VAR() As String
            Get
                Return ResourceManager.GetString("psCANNOT_WRITE_VAR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CMOS.
        '''</summary>
        Friend Shared ReadOnly Property psCMOS() As String
            Get
                Return ResourceManager.GetString("psCMOS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Continue with the next controller?.
        '''</summary>
        Friend Shared ReadOnly Property psCONT_NEXT_RC() As String
            Get
                Return ResourceManager.GetString("psCONT_NEXT_RC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Continue?.
        '''</summary>
        Friend Shared ReadOnly Property psCONTINUE() As String
            Get
                Return ResourceManager.GetString("psCONTINUE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Controller .
        '''</summary>
        Friend Shared ReadOnly Property psCONTROLLER() As String
            Get
                Return ResourceManager.GetString("psCONTROLLER", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Controller Not Available.
        '''</summary>
        Friend Shared ReadOnly Property psCONTROLLER_NOT_AVAILABLE() As String
            Get
                Return ResourceManager.GetString("psCONTROLLER_NOT_AVAILABLE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Copy.
        '''</summary>
        Friend Shared ReadOnly Property psCOPY() As String
            Get
                Return ResourceManager.GetString("psCOPY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Copy to all selected robots.
        '''</summary>
        Friend Shared ReadOnly Property psCOPY_TO_ALL() As String
            Get
                Return ResourceManager.GetString("psCOPY_TO_ALL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Count:.
        '''</summary>
        Friend Shared ReadOnly Property psCOUNT_CAP() As String
            Get
                Return ResourceManager.GetString("psCOUNT_CAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Current Value.
        '''</summary>
        Friend Shared ReadOnly Property psCURRENT_VALUE() As String
            Get
                Return ResourceManager.GetString("psCURRENT_VALUE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Data Error.
        '''</summary>
        Friend Shared ReadOnly Property psDATA_ERROR() As String
            Get
                Return ResourceManager.GetString("psDATA_ERROR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Description:.
        '''</summary>
        Friend Shared ReadOnly Property psDESCRIPTION_CAP() As String
            Get
                Return ResourceManager.GetString("psDESCRIPTION_CAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DRAM.
        '''</summary>
        Friend Shared ReadOnly Property psDRAM() As String
            Get
                Return ResourceManager.GetString("psDRAM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Edit.
        '''</summary>
        Friend Shared ReadOnly Property psEDIT() As String
            Get
                Return ResourceManager.GetString("psEDIT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error while writing variables..
        '''</summary>
        Friend Shared ReadOnly Property psERR_WRT_VAR() As String
            Get
                Return ResourceManager.GetString("psERR_WRT_VAR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error while writing variable to .
        '''</summary>
        Friend Shared ReadOnly Property psERR_WRT_VAR_TO() As String
            Get
                Return ResourceManager.GetString("psERR_WRT_VAR_TO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error..
        '''</summary>
        Friend Shared ReadOnly Property psERROR() As String
            Get
                Return ResourceManager.GetString("psERROR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fast CMOS.
        '''</summary>
        Friend Shared ReadOnly Property psFAST_CMOS() As String
            Get
                Return ResourceManager.GetString("psFAST_CMOS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Group:.
        '''</summary>
        Friend Shared ReadOnly Property psGROUP_CAP() As String
            Get
                Return ResourceManager.GetString("psGROUP_CAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid Data..
        '''</summary>
        Friend Shared ReadOnly Property psINV_DATA() As String
            Get
                Return ResourceManager.GetString("psINV_DATA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid Variable Name.
        '''</summary>
        Friend Shared ReadOnly Property psINVALID_VAR_NAME() As String
            Get
                Return ResourceManager.GetString("psINVALID_VAR_NAME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  is not available..
        '''</summary>
        Friend Shared ReadOnly Property psIS_NOT_AVAILABLE() As String
            Get
                Return ResourceManager.GetString("psIS_NOT_AVAILABLE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  is not valid..
        '''</summary>
        Friend Shared ReadOnly Property psIS_NOT_VALID() As String
            Get
                Return ResourceManager.GetString("psIS_NOT_VALID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to List.
        '''</summary>
        Friend Shared ReadOnly Property psLIST() As String
            Get
                Return ResourceManager.GetString("psLIST", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Maximum:.
        '''</summary>
        Friend Shared ReadOnly Property psMAX_CAP() As String
            Get
                Return ResourceManager.GetString("psMAX_CAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Minimum:.
        '''</summary>
        Friend Shared ReadOnly Property psMIN_CAP() As String
            Get
                Return ResourceManager.GetString("psMIN_CAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to N/A.
        '''</summary>
        Friend Shared ReadOnly Property psNA() As String
            Get
                Return ResourceManager.GetString("psNA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No write access to variable..
        '''</summary>
        Friend Shared ReadOnly Property psNO_WRT_ACC() As String
            Get
                Return ResourceManager.GetString("psNO_WRT_ACC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Not Valid.
        '''</summary>
        Friend Shared ReadOnly Property psNOT_VALID() As String
            Get
                Return ResourceManager.GetString("psNOT_VALID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Numeric data Required.
        '''</summary>
        Friend Shared ReadOnly Property psNUMERIC_REQ() As String
            Get
                Return ResourceManager.GetString("psNUMERIC_REQ", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Program Name:.
        '''</summary>
        Friend Shared ReadOnly Property psPROG_NAME_CAP() As String
            Get
                Return ResourceManager.GetString("psPROG_NAME_CAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Program .
        '''</summary>
        Friend Shared ReadOnly Property psPROGRAM() As String
            Get
                Return ResourceManager.GetString("psPROGRAM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Program Not Available.
        '''</summary>
        Friend Shared ReadOnly Property psPROGRAM_NOT_AVAILABLE() As String
            Get
                Return ResourceManager.GetString("psPROGRAM_NOT_AVAILABLE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Remove.
        '''</summary>
        Friend Shared ReadOnly Property psREMOVE() As String
            Get
                Return ResourceManager.GetString("psREMOVE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Robot Variables.
        '''</summary>
        Friend Shared ReadOnly Property psSCREENCAPTION() As String
            Get
                Return ResourceManager.GetString("psSCREENCAPTION", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select a Variable.
        '''</summary>
        Friend Shared ReadOnly Property psSELECT_VAR() As String
            Get
                Return ResourceManager.GetString("psSELECT_VAR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Set variable to an empty string?.
        '''</summary>
        Friend Shared ReadOnly Property psSET_TO_EMPTY() As String
            Get
                Return ResourceManager.GetString("psSET_TO_EMPTY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Set Empty?.
        '''</summary>
        Friend Shared ReadOnly Property psSETEMPTY() As String
            Get
                Return ResourceManager.GetString("psSETEMPTY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Storage:.
        '''</summary>
        Friend Shared ReadOnly Property psSTORAGE_CAP() As String
            Get
                Return ResourceManager.GetString("psSTORAGE_CAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to String greater than max length..
        '''</summary>
        Friend Shared ReadOnly Property psSTR_GRT_MAX_LEN() As String
            Get
                Return ResourceManager.GetString("psSTR_GRT_MAX_LEN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Length:.
        '''</summary>
        Friend Shared ReadOnly Property psSTR_LEN_CAP() As String
            Get
                Return ResourceManager.GetString("psSTR_LEN_CAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Uninitialized.
        '''</summary>
        Friend Shared ReadOnly Property psUNINITIALIZED() As String
            Get
                Return ResourceManager.GetString("psUNINITIALIZED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Value out of range..
        '''</summary>
        Friend Shared ReadOnly Property psVAL_OUT_RANGE() As String
            Get
                Return ResourceManager.GetString("psVAL_OUT_RANGE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Variable Name:.
        '''</summary>
        Friend Shared ReadOnly Property psVAR_NAME_CAP() As String
            Get
                Return ResourceManager.GetString("psVAR_NAME_CAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Variable Type:.
        '''</summary>
        Friend Shared ReadOnly Property psVAR_TYPE_CAP() As String
            Get
                Return ResourceManager.GetString("psVAR_TYPE_CAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Variable .
        '''</summary>
        Friend Shared ReadOnly Property psVARIABLE() As String
            Get
                Return ResourceManager.GetString("psVARIABLE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Variable name .
        '''</summary>
        Friend Shared ReadOnly Property psVARIABLE_NAME() As String
            Get
                Return ResourceManager.GetString("psVARIABLE_NAME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Variable Not Available.
        '''</summary>
        Friend Shared ReadOnly Property psVARIABLE_NOT_AVAILABLE() As String
            Get
                Return ResourceManager.GetString("psVARIABLE_NOT_AVAILABLE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Write to Selected Controllers.
        '''</summary>
        Friend Shared ReadOnly Property psWRITE_TO_RC() As String
            Get
                Return ResourceManager.GetString("psWRITE_TO_RC", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
