'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4963
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class ProjectStrings
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Notepad.ProjectStrings", GetType(ProjectStrings).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend Shared ReadOnly Property _Next() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_Next", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property Back() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Back", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property FormIcon() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("FormIcon", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend Shared ReadOnly Property forward() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("forward", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property Previous() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Previous", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Center the selected text..
        '''</summary>
        Friend Shared ReadOnly Property psALIGN_CENTER() As String
            Get
                Return ResourceManager.GetString("psALIGN_CENTER", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Left-align the selected text ..
        '''</summary>
        Friend Shared ReadOnly Property psALIGN_LEFT() As String
            Get
                Return ResourceManager.GetString("psALIGN_LEFT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Right-align the selected text..
        '''</summary>
        Friend Shared ReadOnly Property psALIGN_RIGHT() As String
            Get
                Return ResourceManager.GetString("psALIGN_RIGHT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Author.
        '''</summary>
        Friend Shared ReadOnly Property psAUTHOR() As String
            Get
                Return ResourceManager.GetString("psAUTHOR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Name.
        '''</summary>
        Friend Shared ReadOnly Property psAUTHOR_CAP() As String
            Get
                Return ResourceManager.GetString("psAUTHOR_CAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bold text.
        '''</summary>
        Friend Shared ReadOnly Property psBOLD() As String
            Get
                Return ResourceManager.GetString("psBOLD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Case Sensitive..
        '''</summary>
        Friend Shared ReadOnly Property psCASE_SENS() As String
            Get
                Return ResourceManager.GetString("psCASE_SENS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Copy to clipboard.
        '''</summary>
        Friend Shared ReadOnly Property psCOPY_TO_CLIPBOARD() As String
            Get
                Return ResourceManager.GetString("psCOPY_TO_CLIPBOARD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Created.
        '''</summary>
        Friend Shared ReadOnly Property psCREATED() As String
            Get
                Return ResourceManager.GetString("psCREATED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Created.
        '''</summary>
        Friend Shared ReadOnly Property psCREATED_CAP() As String
            Get
                Return ResourceManager.GetString("psCREATED_CAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Creation Date:.
        '''</summary>
        Friend Shared ReadOnly Property psCREATION_DATE() As String
            Get
                Return ResourceManager.GetString("psCREATION_DATE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cut to clipboard.
        '''</summary>
        Friend Shared ReadOnly Property psCUT_TO_CLIPBOARD() As String
            Get
                Return ResourceManager.GetString("psCUT_TO_CLIPBOARD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to database..
        '''</summary>
        Friend Shared ReadOnly Property psDB() As String
            Get
                Return ResourceManager.GetString("psDB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Deleted document: .
        '''</summary>
        Friend Shared ReadOnly Property psDELETE_DOC_CHGLOG() As String
            Get
                Return ResourceManager.GetString("psDELETE_DOC_CHGLOG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Delete document &quot;.
        '''</summary>
        Friend Shared ReadOnly Property psDELETE_DOC1() As String
            Get
                Return ResourceManager.GetString("psDELETE_DOC1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &quot;?.
        '''</summary>
        Friend Shared ReadOnly Property psDELETE_DOC2() As String
            Get
                Return ResourceManager.GetString("psDELETE_DOC2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Delete the open document from the database..
        '''</summary>
        Friend Shared ReadOnly Property psDELETE_DOCUMENT() As String
            Get
                Return ResourceManager.GetString("psDELETE_DOCUMENT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enable Wildcards (?,_,*,%).
        '''</summary>
        Friend Shared ReadOnly Property psENABLE_WILDCARDS() As String
            Get
                Return ResourceManager.GetString("psENABLE_WILDCARDS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to End.
        '''</summary>
        Friend Shared ReadOnly Property psEND() As String
            Get
                Return ResourceManager.GetString("psEND", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Filter.
        '''</summary>
        Friend Shared ReadOnly Property psFILTER() As String
            Get
                Return ResourceManager.GetString("psFILTER", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Filter document list.
        '''</summary>
        Friend Shared ReadOnly Property psFILTER_FRM_CAP() As String
            Get
                Return ResourceManager.GetString("psFILTER_FRM_CAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Filter the list by author, subject, or date..
        '''</summary>
        Friend Shared ReadOnly Property psFILTER_LIST() As String
            Get
                Return ResourceManager.GetString("psFILTER_LIST", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Search the list or current document..
        '''</summary>
        Friend Shared ReadOnly Property psFIND() As String
            Get
                Return ResourceManager.GetString("psFIND", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Find.
        '''</summary>
        Friend Shared ReadOnly Property psFIND_FRM_CAP() As String
            Get
                Return ResourceManager.GetString("psFIND_FRM_CAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Find text in this document or search the list..
        '''</summary>
        Friend Shared ReadOnly Property psFIND_TOOLTIP() As String
            Get
                Return ResourceManager.GetString("psFIND_TOOLTIP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hide.
        '''</summary>
        Friend Shared ReadOnly Property psHIDE() As String
            Get
                Return ResourceManager.GetString("psHIDE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hide document list..
        '''</summary>
        Friend Shared ReadOnly Property psHIDE_LIST() As String
            Get
                Return ResourceManager.GetString("psHIDE_LIST", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ID.
        '''</summary>
        Friend Shared ReadOnly Property psID_CAP() As String
            Get
                Return ResourceManager.GetString("psID_CAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Italic text.
        '''</summary>
        Friend Shared ReadOnly Property psITALIC() As String
            Get
                Return ResourceManager.GetString("psITALIC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Modified.
        '''</summary>
        Friend Shared ReadOnly Property psMODIFIED() As String
            Get
                Return ResourceManager.GetString("psMODIFIED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Modified.
        '''</summary>
        Friend Shared ReadOnly Property psMODIFIED_CAP() As String
            Get
                Return ResourceManager.GetString("psMODIFIED_CAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Modified Date:.
        '''</summary>
        Friend Shared ReadOnly Property psMODIFIED_DATE() As String
            Get
                Return ResourceManager.GetString("psMODIFIED_DATE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Name the Document..
        '''</summary>
        Friend Shared ReadOnly Property psNAME_FRM_CAP() As String
            Get
                Return ResourceManager.GetString("psNAME_FRM_CAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Created new document: .
        '''</summary>
        Friend Shared ReadOnly Property psNEW_DOC_CHGLOG() As String
            Get
                Return ResourceManager.GetString("psNEW_DOC_CHGLOG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Create a new document..
        '''</summary>
        Friend Shared ReadOnly Property psNEW_DOCUMENT() As String
            Get
                Return ResourceManager.GetString("psNEW_DOCUMENT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New Document.
        '''</summary>
        Friend Shared ReadOnly Property psNEW_FRM_CAP() As String
            Get
                Return ResourceManager.GetString("psNEW_FRM_CAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enter the Title for the new document:.
        '''</summary>
        Friend Shared ReadOnly Property psNEW_TITLE() As String
            Get
                Return ResourceManager.GetString("psNEW_TITLE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Next.
        '''</summary>
        Friend Shared ReadOnly Property psNEXT() As String
            Get
                Return ResourceManager.GetString("psNEXT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Next &gt;&gt;.
        '''</summary>
        Friend Shared ReadOnly Property psNEXT_BTN() As String
            Get
                Return ResourceManager.GetString("psNEXT_BTN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Open the next document in the list..
        '''</summary>
        Friend Shared ReadOnly Property psNEXT_DOC() As String
            Get
                Return ResourceManager.GetString("psNEXT_DOC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No records found..
        '''</summary>
        Friend Shared ReadOnly Property psNO_RECORDS_FOUND() As String
            Get
                Return ResourceManager.GetString("psNO_RECORDS_FOUND", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Open document &quot;.
        '''</summary>
        Friend Shared ReadOnly Property psOPEN_DOC_TO1() As String
            Get
                Return ResourceManager.GetString("psOPEN_DOC_TO1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &quot;.  Save as topic &quot;.
        '''</summary>
        Friend Shared ReadOnly Property psOPEN_DOC_TO2() As String
            Get
                Return ResourceManager.GetString("psOPEN_DOC_TO2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &quot;.
        '''</summary>
        Friend Shared ReadOnly Property psOPEN_DOC_TO3() As String
            Get
                Return ResourceManager.GetString("psOPEN_DOC_TO3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Open a file..
        '''</summary>
        Friend Shared ReadOnly Property psOPEN_DOCUMENT() As String
            Get
                Return ResourceManager.GetString("psOPEN_DOCUMENT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Paste from clipboard.
        '''</summary>
        Friend Shared ReadOnly Property psPASTE_FROM_CLIPBOARD() As String
            Get
                Return ResourceManager.GetString("psPASTE_FROM_CLIPBOARD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Previous.
        '''</summary>
        Friend Shared ReadOnly Property psPREV() As String
            Get
                Return ResourceManager.GetString("psPREV", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;&lt; Previous.
        '''</summary>
        Friend Shared ReadOnly Property psPREV_BTN() As String
            Get
                Return ResourceManager.GetString("psPREV_BTN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Open the previous document in the list..
        '''</summary>
        Friend Shared ReadOnly Property psPREV_DOC() As String
            Get
                Return ResourceManager.GetString("psPREV_DOC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Print document.
        '''</summary>
        Friend Shared ReadOnly Property psPRINT_DOCUMENT() As String
            Get
                Return ResourceManager.GetString("psPRINT_DOCUMENT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Properties.
        '''</summary>
        Friend Shared ReadOnly Property psPROP_FRM_CAP() As String
            Get
                Return ResourceManager.GetString("psPROP_FRM_CAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Record Not Found.
        '''</summary>
        Friend Shared ReadOnly Property psRECORD_NOT_FOUND() As String
            Get
                Return ResourceManager.GetString("psRECORD_NOT_FOUND", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to rich text (*.RTF) file..
        '''</summary>
        Friend Shared ReadOnly Property psRTF_FILR() As String
            Get
                Return ResourceManager.GetString("psRTF_FILR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Saved document to the database: .
        '''</summary>
        Friend Shared ReadOnly Property psSAVE_DOC_DB_CHGLOG() As String
            Get
                Return ResourceManager.GetString("psSAVE_DOC_DB_CHGLOG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save document to .
        '''</summary>
        Friend Shared ReadOnly Property psSAVE_DOC_TO() As String
            Get
                Return ResourceManager.GetString("psSAVE_DOC_TO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save document..
        '''</summary>
        Friend Shared ReadOnly Property psSAVE_DOCCUMENT() As String
            Get
                Return ResourceManager.GetString("psSAVE_DOCCUMENT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Saved document &quot;.
        '''</summary>
        Friend Shared ReadOnly Property psSAVED_DOC_TO1() As String
            Get
                Return ResourceManager.GetString("psSAVED_DOC_TO1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &quot; to .
        '''</summary>
        Friend Shared ReadOnly Property psSAVED_DOC_TO2() As String
            Get
                Return ResourceManager.GetString("psSAVED_DOC_TO2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Notepad.
        '''</summary>
        Friend Shared ReadOnly Property psSCREENCAPTION() As String
            Get
                Return ResourceManager.GetString("psSCREENCAPTION", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Search All Documents..
        '''</summary>
        Friend Shared ReadOnly Property psSEARCH_ALL_DOCS() As String
            Get
                Return ResourceManager.GetString("psSEARCH_ALL_DOCS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Search This Document..
        '''</summary>
        Friend Shared ReadOnly Property psSEARCH_THIS_DOC() As String
            Get
                Return ResourceManager.GetString("psSEARCH_THIS_DOC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Search Topics..
        '''</summary>
        Friend Shared ReadOnly Property psSEARCH_TOPICS() As String
            Get
                Return ResourceManager.GetString("psSEARCH_TOPICS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select Document.
        '''</summary>
        Friend Shared ReadOnly Property psSELECT_DOC() As String
            Get
                Return ResourceManager.GetString("psSELECT_DOC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Show.
        '''</summary>
        Friend Shared ReadOnly Property psSHOW() As String
            Get
                Return ResourceManager.GetString("psSHOW", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Show document list..
        '''</summary>
        Friend Shared ReadOnly Property psSHOW_LIST() As String
            Get
                Return ResourceManager.GetString("psSHOW_LIST", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Start.
        '''</summary>
        Friend Shared ReadOnly Property psSTART() As String
            Get
                Return ResourceManager.GetString("psSTART", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Text.
        '''</summary>
        Friend Shared ReadOnly Property psTEXT_CAP() As String
            Get
                Return ResourceManager.GetString("psTEXT_CAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Text Not Found..
        '''</summary>
        Friend Shared ReadOnly Property psTEXT_NOT_FOUND() As String
            Get
                Return ResourceManager.GetString("psTEXT_NOT_FOUND", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Topic.
        '''</summary>
        Friend Shared ReadOnly Property psTOPIC() As String
            Get
                Return ResourceManager.GetString("psTOPIC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Topic.
        '''</summary>
        Friend Shared ReadOnly Property psTOPIC_CAP() As String
            Get
                Return ResourceManager.GetString("psTOPIC_CAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to text(*.TXT) file..
        '''</summary>
        Friend Shared ReadOnly Property psTXT_FILE() As String
            Get
                Return ResourceManager.GetString("psTXT_FILE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Underline the selected text..
        '''</summary>
        Friend Shared ReadOnly Property psUNDERLINE() As String
            Get
                Return ResourceManager.GetString("psUNDERLINE", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
