'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5448
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'This class was auto-generated by the StronglyTypedResourceBuilder
'class via a tool like ResGen or Visual Studio.
'To add or remove a member, edit your .ResX file then rerun ResGen
'with the /str option, or rebuild your VS project.
'''<summary>
'''  A strongly-typed resource class, for looking up localized strings, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Friend Class Devices
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Returns the cached ResourceManager instance used by this class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("BSD.Devices", GetType(Devices).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Overrides the current thread's CurrentUICulture property for all
    '''  resource lookups using this strongly typed resource class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Held for Ghost Simulation.
    '''</summary>
    Friend Shared ReadOnly Property dpsZoneOff08() As String
        Get
            Return ResourceManager.GetString("dpsZoneOff08", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to No Job entering During Ghost.
    '''</summary>
    Friend Shared ReadOnly Property dpsZoneOn07() As String
        Get
            Return ResourceManager.GetString("dpsZoneOn07", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Device Status For Conveyor Interlocks.
    '''</summary>
    Friend Shared ReadOnly Property dsDeviceScreen() As String
        Get
            Return ResourceManager.GetString("dsDeviceScreen", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Holding Conveyor Untill Home.
    '''</summary>
    Friend Shared ReadOnly Property dsRobotOff01() As String
        Get
            Return ResourceManager.GetString("dsRobotOff01", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Waiting for Cancel or Continue.
    '''</summary>
    Friend Shared ReadOnly Property dsRobotOff02() As String
        Get
            Return ResourceManager.GetString("dsRobotOff02", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Waiting for Color Change.
    '''</summary>
    Friend Shared ReadOnly Property dsRobotOff03() As String
        Get
            Return ResourceManager.GetString("dsRobotOff03", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Not Running.
    '''</summary>
    Friend Shared ReadOnly Property dsRobotOff04() As String
        Get
            Return ResourceManager.GetString("dsRobotOff04", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to .
    '''</summary>
    Friend Shared ReadOnly Property dsRobotOff05() As String
        Get
            Return ResourceManager.GetString("dsRobotOff05", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to .
    '''</summary>
    Friend Shared ReadOnly Property dsRobotOff06() As String
        Get
            Return ResourceManager.GetString("dsRobotOff06", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to .
    '''</summary>
    Friend Shared ReadOnly Property dsRobotOff07() As String
        Get
            Return ResourceManager.GetString("dsRobotOff07", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to .
    '''</summary>
    Friend Shared ReadOnly Property dsRobotOff08() As String
        Get
            Return ResourceManager.GetString("dsRobotOff08", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Not Waiting for Home.
    '''</summary>
    Friend Shared ReadOnly Property dsRobotOn01() As String
        Get
            Return ResourceManager.GetString("dsRobotOn01", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Not Waiting for Cancel or Continue.
    '''</summary>
    Friend Shared ReadOnly Property dsRobotOn02() As String
        Get
            Return ResourceManager.GetString("dsRobotOn02", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Not Waiting for Color Change.
    '''</summary>
    Friend Shared ReadOnly Property dsRobotOn03() As String
        Get
            Return ResourceManager.GetString("dsRobotOn03", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Running or Bypassed.
    '''</summary>
    Friend Shared ReadOnly Property dsRobotOn04() As String
        Get
            Return ResourceManager.GetString("dsRobotOn04", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to .
    '''</summary>
    Friend Shared ReadOnly Property dsRobotOn05() As String
        Get
            Return ResourceManager.GetString("dsRobotOn05", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to .
    '''</summary>
    Friend Shared ReadOnly Property dsRobotOn06() As String
        Get
            Return ResourceManager.GetString("dsRobotOn06", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to .
    '''</summary>
    Friend Shared ReadOnly Property dsRobotOn07() As String
        Get
            Return ResourceManager.GetString("dsRobotOn07", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to .
    '''</summary>
    Friend Shared ReadOnly Property dsRobotOn08() As String
        Get
            Return ResourceManager.GetString("dsRobotOn08", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Intrusion Not OK.
    '''</summary>
    Friend Shared ReadOnly Property dsZoneOff01() As String
        Get
            Return ResourceManager.GetString("dsZoneOff01", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Zone E-stop Not OK.
    '''</summary>
    Friend Shared ReadOnly Property dsZoneOff02() As String
        Get
            Return ResourceManager.GetString("dsZoneOff02", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Booth Doors Not OK.
    '''</summary>
    Friend Shared ReadOnly Property dsZoneOff03() As String
        Get
            Return ResourceManager.GetString("dsZoneOff03", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Booth Interlocks Not OK.
    '''</summary>
    Friend Shared ReadOnly Property dsZoneOff04() As String
        Get
            Return ResourceManager.GetString("dsZoneOff04", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to .
    '''</summary>
    Friend Shared ReadOnly Property dsZoneOff05() As String
        Get
            Return ResourceManager.GetString("dsZoneOff05", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Invalid Job Data.
    '''</summary>
    Friend Shared ReadOnly Property dsZoneOff06() As String
        Get
            Return ResourceManager.GetString("dsZoneOff06", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Job Entered Zone During Ghost.
    '''</summary>
    Friend Shared ReadOnly Property dsZoneOff07() As String
        Get
            Return ResourceManager.GetString("dsZoneOff07", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Holding Conveyor For Ghost Sim.
    '''</summary>
    Friend Shared ReadOnly Property dsZoneOff08() As String
        Get
            Return ResourceManager.GetString("dsZoneOff08", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Jog Functions Enabled.
    '''</summary>
    Friend Shared ReadOnly Property dsZoneOff09() As String
        Get
            Return ResourceManager.GetString("dsZoneOff09", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Conveyor Held at SOC.
    '''</summary>
    Friend Shared ReadOnly Property dsZoneOff10() As String
        Get
            Return ResourceManager.GetString("dsZoneOff10", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Robot Rack Faults.
    '''</summary>
    Friend Shared ReadOnly Property dsZoneOff11() As String
        Get
            Return ResourceManager.GetString("dsZoneOff11", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to .
    '''</summary>
    Friend Shared ReadOnly Property dsZoneOff12() As String
        Get
            Return ResourceManager.GetString("dsZoneOff12", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to .
    '''</summary>
    Friend Shared ReadOnly Property dsZoneOff13() As String
        Get
            Return ResourceManager.GetString("dsZoneOff13", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to .
    '''</summary>
    Friend Shared ReadOnly Property dsZoneOff14() As String
        Get
            Return ResourceManager.GetString("dsZoneOff14", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to .
    '''</summary>
    Friend Shared ReadOnly Property dsZoneOff15() As String
        Get
            Return ResourceManager.GetString("dsZoneOff15", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to .
    '''</summary>
    Friend Shared ReadOnly Property dsZoneOff16() As String
        Get
            Return ResourceManager.GetString("dsZoneOff16", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Intrusion OK.
    '''</summary>
    Friend Shared ReadOnly Property dsZoneOn01() As String
        Get
            Return ResourceManager.GetString("dsZoneOn01", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Zone E-stop OK.
    '''</summary>
    Friend Shared ReadOnly Property dsZoneOn02() As String
        Get
            Return ResourceManager.GetString("dsZoneOn02", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Booth Doors OK.
    '''</summary>
    Friend Shared ReadOnly Property dsZoneOn03() As String
        Get
            Return ResourceManager.GetString("dsZoneOn03", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Booth Interlocks OK.
    '''</summary>
    Friend Shared ReadOnly Property dsZoneOn04() As String
        Get
            Return ResourceManager.GetString("dsZoneOn04", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to .
    '''</summary>
    Friend Shared ReadOnly Property dsZoneOn05() As String
        Get
            Return ResourceManager.GetString("dsZoneOn05", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to No Invalid Job Data.
    '''</summary>
    Friend Shared ReadOnly Property dsZoneOn06() As String
        Get
            Return ResourceManager.GetString("dsZoneOn06", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Queue Empty For Ghost.
    '''</summary>
    Friend Shared ReadOnly Property dsZoneOn07() As String
        Get
            Return ResourceManager.GetString("dsZoneOn07", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to No Hold for Ghost-Simulation.
    '''</summary>
    Friend Shared ReadOnly Property dsZoneOn08() As String
        Get
            Return ResourceManager.GetString("dsZoneOn08", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Jog Functions Disabled.
    '''</summary>
    Friend Shared ReadOnly Property dsZoneOn09() As String
        Get
            Return ResourceManager.GetString("dsZoneOn09", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Conveyor Not Held at SOC.
    '''</summary>
    Friend Shared ReadOnly Property dsZoneOn10() As String
        Get
            Return ResourceManager.GetString("dsZoneOn10", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to No Robot Rack Faults.
    '''</summary>
    Friend Shared ReadOnly Property dsZoneOn11() As String
        Get
            Return ResourceManager.GetString("dsZoneOn11", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to .
    '''</summary>
    Friend Shared ReadOnly Property dsZoneOn12() As String
        Get
            Return ResourceManager.GetString("dsZoneOn12", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to .
    '''</summary>
    Friend Shared ReadOnly Property dsZoneOn13() As String
        Get
            Return ResourceManager.GetString("dsZoneOn13", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to .
    '''</summary>
    Friend Shared ReadOnly Property dsZoneOn14() As String
        Get
            Return ResourceManager.GetString("dsZoneOn14", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to .
    '''</summary>
    Friend Shared ReadOnly Property dsZoneOn15() As String
        Get
            Return ResourceManager.GetString("dsZoneOn15", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to .
    '''</summary>
    Friend Shared ReadOnly Property dsZoneOn16() As String
        Get
            Return ResourceManager.GetString("dsZoneOn16", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to TP E-stop Not OK.
    '''</summary>
    Friend Shared ReadOnly Property psRobotOff09() As String
        Get
            Return ResourceManager.GetString("psRobotOff09", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to SOP E-stop Not OK.
    '''</summary>
    Friend Shared ReadOnly Property psRobotOff10() As String
        Get
            Return ResourceManager.GetString("psRobotOff10", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to TP E-stop OK.
    '''</summary>
    Friend Shared ReadOnly Property psRobotOn09() As String
        Get
            Return ResourceManager.GetString("psRobotOn09", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to SOPE-stop OK.
    '''</summary>
    Friend Shared ReadOnly Property psRobotOn10() As String
        Get
            Return ResourceManager.GetString("psRobotOn10", resourceCulture)
        End Get
    End Property
End Class
