'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5446
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class ProjectStrings
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Reports.ProjectStrings", GetType(ProjectStrings).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend Shared ReadOnly Property criteria() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("criteria", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property FormIcon() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("FormIcon", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Adjusting records for break times....
        '''</summary>
        Friend Shared ReadOnly Property psADJUST_FOR_BREAK() As String
            Get
                Return ResourceManager.GetString("psADJUST_FOR_BREAK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Adjust Time.
        '''</summary>
        Friend Shared ReadOnly Property psADJUST_TIME() As String
            Get
                Return ResourceManager.GetString("psADJUST_TIME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Alarm.
        '''</summary>
        Friend Shared ReadOnly Property psALARM_CAP() As String
            Get
                Return ResourceManager.GetString("psALARM_CAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Alarm Log Reporting.
        '''</summary>
        Friend Shared ReadOnly Property psALARM_REPORT() As String
            Get
                Return ResourceManager.GetString("psALARM_REPORT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Alarms.
        '''</summary>
        Friend Shared ReadOnly Property psALARMS_SHEET_NAME() As String
            Get
                Return ResourceManager.GetString("psALARMS_SHEET_NAME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to All Alarms.
        '''</summary>
        Friend Shared ReadOnly Property psALL_ALARMS() As String
            Get
                Return ResourceManager.GetString("psALL_ALARMS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Both.
        '''</summary>
        Friend Shared ReadOnly Property psBOTH_CAP() As String
            Get
                Return ResourceManager.GetString("psBOTH_CAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Break Active.
        '''</summary>
        Friend Shared ReadOnly Property psBREAK_ACTIVE_DESC() As String
            Get
                Return ResourceManager.GetString("psBREAK_ACTIVE_DESC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Building Chart.
        '''</summary>
        Friend Shared ReadOnly Property psBUILDING_CHART() As String
            Get
                Return ResourceManager.GetString("psBUILDING_CHART", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Building Table.
        '''</summary>
        Friend Shared ReadOnly Property psBUILDING_TABLE() As String
            Get
                Return ResourceManager.GetString("psBUILDING_TABLE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to By Duration.
        '''</summary>
        Friend Shared ReadOnly Property psBY_DURATION() As String
            Get
                Return ResourceManager.GetString("psBY_DURATION", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to By Occurrence.
        '''</summary>
        Friend Shared ReadOnly Property psBY_Occurrence() As String
            Get
                Return ResourceManager.GetString("psBY_Occurrence", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to TPSU.
        '''</summary>
        Friend Shared ReadOnly Property psCANNISTER_TPSU_CAP() As String
            Get
                Return ResourceManager.GetString("psCANNISTER_TPSU_CAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Carrier.
        '''</summary>
        Friend Shared ReadOnly Property psCARRIER_CAP() As String
            Get
                Return ResourceManager.GetString("psCARRIER_CAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Category.
        '''</summary>
        Friend Shared ReadOnly Property psCATEGORY_CAP() As String
            Get
                Return ResourceManager.GetString("psCATEGORY_CAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CC Time (sec).
        '''</summary>
        Friend Shared ReadOnly Property psCC_TIME_CAP() As String
            Get
                Return ResourceManager.GetString("psCC_TIME_CAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Change Log Reporting.
        '''</summary>
        Friend Shared ReadOnly Property psCHANGE_REPORT() As String
            Get
                Return ResourceManager.GetString("psCHANGE_REPORT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chart.
        '''</summary>
        Friend Shared ReadOnly Property psCHART() As String
            Get
                Return ResourceManager.GetString("psCHART", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Check alarm records.
        '''</summary>
        Friend Shared ReadOnly Property psCHECK_ALARM_RECORDS() As String
            Get
                Return ResourceManager.GetString("psCHECK_ALARM_RECORDS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Check production records.
        '''</summary>
        Friend Shared ReadOnly Property psCHECK_PROC_RECORDS() As String
            Get
                Return ResourceManager.GetString("psCHECK_PROC_RECORDS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Color.
        '''</summary>
        Friend Shared ReadOnly Property psCOLOR_CAP() As String
            Get
                Return ResourceManager.GetString("psCOLOR_CAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Complete Time.
        '''</summary>
        Friend Shared ReadOnly Property psCOMPLETE_TIME_CAP() As String
            Get
                Return ResourceManager.GetString("psCOMPLETE_TIME_CAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Conveyor Reporting.
        '''</summary>
        Friend Shared ReadOnly Property psCONVEYOR_REPORT() As String
            Get
                Return ResourceManager.GetString("psCONVEYOR_REPORT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Creating Spreadsheet File..
        '''</summary>
        Friend Shared ReadOnly Property psCREATING_SPREADSHEET_FILE() As String
            Get
                Return ResourceManager.GetString("psCREATING_SPREADSHEET_FILE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Conveyor Currently Held By FANUC.
        '''</summary>
        Friend Shared ReadOnly Property psCUR_CONV_HELD_FANUC() As String
            Get
                Return ResourceManager.GetString("psCUR_CONV_HELD_FANUC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Conveyor Currently Held By Others.
        '''</summary>
        Friend Shared ReadOnly Property psCUR_CONV_HELD_OTHERS() As String
            Get
                Return ResourceManager.GetString("psCUR_CONV_HELD_OTHERS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Conveyor Currently Running.
        '''</summary>
        Friend Shared ReadOnly Property psCUR_CONV_RUNNING() As String
            Get
                Return ResourceManager.GetString("psCUR_CONV_RUNNING", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cycle Time (sec).
        '''</summary>
        Friend Shared ReadOnly Property psCYCLE_TIME_CAP() As String
            Get
                Return ResourceManager.GetString("psCYCLE_TIME_CAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to M/d h:mm:ss.ff.
        '''</summary>
        Friend Shared ReadOnly Property psDATETIME_FORMAT1() As String
            Get
                Return ResourceManager.GetString("psDATETIME_FORMAT1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to M/d h:mm tt.
        '''</summary>
        Friend Shared ReadOnly Property psDATETIME_FORMAT2() As String
            Get
                Return ResourceManager.GetString("psDATETIME_FORMAT2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Degrade.
        '''</summary>
        Friend Shared ReadOnly Property psDEGRADE_STATUS_CAP() As String
            Get
                Return ResourceManager.GetString("psDEGRADE_STATUS_CAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Description.
        '''</summary>
        Friend Shared ReadOnly Property psDESC_CAP() As String
            Get
                Return ResourceManager.GetString("psDESC_CAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Downtime Alarms.
        '''</summary>
        Friend Shared ReadOnly Property psDOWNTIME_ALARMS() As String
            Get
                Return ResourceManager.GetString("psDOWNTIME_ALARMS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Downtime Reporting.
        '''</summary>
        Friend Shared ReadOnly Property psDOWNTIME_REPORT() As String
            Get
                Return ResourceManager.GetString("psDOWNTIME_REPORT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Duration.
        '''</summary>
        Friend Shared ReadOnly Property psDURATION_CAP() As String
            Get
                Return ResourceManager.GetString("psDURATION_CAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Duration(%).
        '''</summary>
        Friend Shared ReadOnly Property psDURATION_PERC_CAP() As String
            Get
                Return ResourceManager.GetString("psDURATION_PERC_CAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DurationSummary.
        '''</summary>
        Friend Shared ReadOnly Property psDURATION_SUMMARY_SHEET_NAME() As String
            Get
                Return ResourceManager.GetString("psDURATION_SUMMARY_SHEET_NAME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to End.
        '''</summary>
        Friend Shared ReadOnly Property psEND() As String
            Get
                Return ResourceManager.GetString("psEND", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to End Time.
        '''</summary>
        Friend Shared ReadOnly Property psEND_TIME_CAP() As String
            Get
                Return ResourceManager.GetString("psEND_TIME_CAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select an end time that is later than the start time..
        '''</summary>
        Friend Shared ReadOnly Property psEND_TIME_LATER() As String
            Get
                Return ResourceManager.GetString("psEND_TIME_LATER", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error: Failed to save file.
        '''</summary>
        Friend Shared ReadOnly Property psERR_FAILED_TO_SAVE_FILE() As String
            Get
                Return ResourceManager.GetString("psERR_FAILED_TO_SAVE_FILE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Filtering Oneshot Alarms....
        '''</summary>
        Friend Shared ReadOnly Property psFILTER_ONESHOT_ALARMS() As String
            Get
                Return ResourceManager.GetString("psFILTER_ONESHOT_ALARMS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Finding Chart Data.
        '''</summary>
        Friend Shared ReadOnly Property psFINDING_CHART_DATA() As String
            Get
                Return ResourceManager.GetString("psFINDING_CHART_DATA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Formatting report.....
        '''</summary>
        Friend Shared ReadOnly Property psFORMATTING() As String
            Get
                Return ResourceManager.GetString("psFORMATTING", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to From.
        '''</summary>
        Friend Shared ReadOnly Property psFROM() As String
            Get
                Return ResourceManager.GetString("psFROM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Full Help File.
        '''</summary>
        Friend Shared ReadOnly Property psFULL_FILE() As String
            Get
                Return ResourceManager.GetString("psFULL_FILE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Getting Break Times....
        '''</summary>
        Friend Shared ReadOnly Property psGETTING_BREAK_ALRM() As String
            Get
                Return ResourceManager.GetString("psGETTING_BREAK_ALRM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Getting Conveyor Alarms....
        '''</summary>
        Friend Shared ReadOnly Property psGETTING_CONV_ALARMS() As String
            Get
                Return ResourceManager.GetString("psGETTING_CONV_ALARMS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Retrieving data from database....
        '''</summary>
        Friend Shared ReadOnly Property psGETTING_DATA() As String
            Get
                Return ResourceManager.GetString("psGETTING_DATA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Getting Downtime Alarm Data....
        '''</summary>
        Friend Shared ReadOnly Property psGETTING_DT_DATA() As String
            Get
                Return ResourceManager.GetString("psGETTING_DT_DATA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ghost.
        '''</summary>
        Friend Shared ReadOnly Property psGHOST_STATUS_CAP() As String
            Get
                Return ResourceManager.GetString("psGHOST_STATUS_CAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Data retrieved.
        '''</summary>
        Friend Shared ReadOnly Property psGOT_DATA() As String
            Get
                Return ResourceManager.GetString("psGOT_DATA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unable to retrieve data.
        '''</summary>
        Friend Shared ReadOnly Property psGOT_NO_DATA() As String
            Get
                Return ResourceManager.GetString("psGOT_NO_DATA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chart.
        '''</summary>
        Friend Shared ReadOnly Property psGRAPH_SHEET_NAME() As String
            Get
                Return ResourceManager.GetString("psGRAPH_SHEET_NAME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Alarm Cause/Remedy Information.
        '''</summary>
        Friend Shared ReadOnly Property psHELP_FORM_CAP() As String
            Get
                Return ResourceManager.GetString("psHELP_FORM_CAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (h:mm:ss).
        '''</summary>
        Friend Shared ReadOnly Property psHMS() As String
            Get
                Return ResourceManager.GetString("psHMS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Include Held By Others.
        '''</summary>
        Friend Shared ReadOnly Property psINCLUDE_HBO() As String
            Get
                Return ResourceManager.GetString("psINCLUDE_HBO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Init String.
        '''</summary>
        Friend Shared ReadOnly Property psINIT_STRING_CAP() As String
            Get
                Return ResourceManager.GetString("psINIT_STRING_CAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Item.
        '''</summary>
        Friend Shared ReadOnly Property psITEM_CAP() As String
            Get
                Return ResourceManager.GetString("psITEM_CAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Job Report.
        '''</summary>
        Friend Shared ReadOnly Property psJOB_REPORT_CAP() As String
            Get
                Return ResourceManager.GetString("psJOB_REPORT_CAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Job Status.
        '''</summary>
        Friend Shared ReadOnly Property psJOB_STATUS_CAP() As String
            Get
                Return ResourceManager.GetString("psJOB_STATUS_CAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unknown.
        '''</summary>
        Friend Shared ReadOnly Property psJOB_STATUS00() As String
            Get
                Return ResourceManager.GetString("psJOB_STATUS00", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Complete.
        '''</summary>
        Friend Shared ReadOnly Property psJOB_STATUS01() As String
            Get
                Return ResourceManager.GetString("psJOB_STATUS01", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Complete w\Line Stop.
        '''</summary>
        Friend Shared ReadOnly Property psJOB_STATUS02() As String
            Get
                Return ResourceManager.GetString("psJOB_STATUS02", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Complete w\Error.
        '''</summary>
        Friend Shared ReadOnly Property psJOB_STATUS03() As String
            Get
                Return ResourceManager.GetString("psJOB_STATUS03", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Aborted.
        '''</summary>
        Friend Shared ReadOnly Property psJOB_STATUS04() As String
            Get
                Return ResourceManager.GetString("psJOB_STATUS04", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No Paint.
        '''</summary>
        Friend Shared ReadOnly Property psJOB_STATUS05() As String
            Get
                Return ResourceManager.GetString("psJOB_STATUS05", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid Data.
        '''</summary>
        Friend Shared ReadOnly Property psJOB_STATUS06() As String
            Get
                Return ResourceManager.GetString("psJOB_STATUS06", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Not Required.
        '''</summary>
        Friend Shared ReadOnly Property psJOB_STATUS07() As String
            Get
                Return ResourceManager.GetString("psJOB_STATUS07", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ghost.
        '''</summary>
        Friend Shared ReadOnly Property psJOB_STATUS08() As String
            Get
                Return ResourceManager.GetString("psJOB_STATUS08", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bypassed.
        '''</summary>
        Friend Shared ReadOnly Property psJOB_STATUS09() As String
            Get
                Return ResourceManager.GetString("psJOB_STATUS09", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ghost - Complete w/ Error.
        '''</summary>
        Friend Shared ReadOnly Property psJOB_STATUS10() As String
            Get
                Return ResourceManager.GetString("psJOB_STATUS10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ghost - Aborted.
        '''</summary>
        Friend Shared ReadOnly Property psJOB_STATUS11() As String
            Get
                Return ResourceManager.GetString("psJOB_STATUS11", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ghost - Not Required.
        '''</summary>
        Friend Shared ReadOnly Property psJOB_STATUS12() As String
            Get
                Return ResourceManager.GetString("psJOB_STATUS12", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ghost - Bypassed.
        '''</summary>
        Friend Shared ReadOnly Property psJOB_STATUS13() As String
            Get
                Return ResourceManager.GetString("psJOB_STATUS13", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No Status.
        '''</summary>
        Friend Shared ReadOnly Property psJOB_STATUS14() As String
            Get
                Return ResourceManager.GetString("psJOB_STATUS14", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No Status.
        '''</summary>
        Friend Shared ReadOnly Property psJOB_STATUS15() As String
            Get
                Return ResourceManager.GetString("psJOB_STATUS15", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Job Name.
        '''</summary>
        Friend Shared ReadOnly Property psJOBNAME_CAP() As String
            Get
                Return ResourceManager.GetString("psJOBNAME_CAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Last Week.
        '''</summary>
        Friend Shared ReadOnly Property psLAST_WEEK() As String
            Get
                Return ResourceManager.GetString("psLAST_WEEK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Last Week&apos;s.
        '''</summary>
        Friend Shared ReadOnly Property psLAST_WEEK_TITLE_PRE() As String
            Get
                Return ResourceManager.GetString("psLAST_WEEK_TITLE_PRE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to LastWeek.
        '''</summary>
        Friend Shared ReadOnly Property psLASTWEEK() As String
            Get
                Return ResourceManager.GetString("psLASTWEEK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This type of report is limited to 100 hours. Adjust end time?.
        '''</summary>
        Friend Shared ReadOnly Property psLIMIT_TO_100_HOURS() As String
            Get
                Return ResourceManager.GetString("psLIMIT_TO_100_HOURS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to There are %s records. Are you sure you want to print?.
        '''</summary>
        Friend Shared ReadOnly Property psLOTSA_RECORDS() As String
            Get
                Return ResourceManager.GetString("psLOTSA_RECORDS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Material Learned.
        '''</summary>
        Friend Shared ReadOnly Property psMATERIAL_LEARNED_CAP() As String
            Get
                Return ResourceManager.GetString("psMATERIAL_LEARNED_CAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Material Learned 2.
        '''</summary>
        Friend Shared ReadOnly Property psMATERIAL_LEARNED2_CAP() As String
            Get
                Return ResourceManager.GetString("psMATERIAL_LEARNED2_CAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Material Temp.
        '''</summary>
        Friend Shared ReadOnly Property psMATERIAL_TEMP_CAP() As String
            Get
                Return ResourceManager.GetString("psMATERIAL_TEMP_CAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Material Temp 2.
        '''</summary>
        Friend Shared ReadOnly Property psMATERIAL_TEMP2_CAP() As String
            Get
                Return ResourceManager.GetString("psMATERIAL_TEMP2_CAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Most Recent.
        '''</summary>
        Friend Shared ReadOnly Property psMOST_RECENT() As String
            Get
                Return ResourceManager.GetString("psMOST_RECENT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MTBF.
        '''</summary>
        Friend Shared ReadOnly Property psMTBF() As String
            Get
                Return ResourceManager.GetString("psMTBF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MTTR.
        '''</summary>
        Friend Shared ReadOnly Property psMTTR() As String
            Get
                Return ResourceManager.GetString("psMTTR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No break time found..
        '''</summary>
        Friend Shared ReadOnly Property psNO_BREAK_FOUND() As String
            Get
                Return ResourceManager.GetString("psNO_BREAK_FOUND", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No Records Found..
        '''</summary>
        Friend Shared ReadOnly Property psNO_RECORDS() As String
            Get
                Return ResourceManager.GetString("psNO_RECORDS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Node.
        '''</summary>
        Friend Shared ReadOnly Property psNODE_CAP() As String
            Get
                Return ResourceManager.GetString("psNODE_CAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to OccurrenceSummary.
        '''</summary>
        Friend Shared ReadOnly Property psOCCURRENCE_SUMMARY_SHEET_NAME() As String
            Get
                Return ResourceManager.GetString("psOCCURRENCE_SUMMARY_SHEET_NAME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Occurrences.
        '''</summary>
        Friend Shared ReadOnly Property psOCCURRENCES_CAP() As String
            Get
                Return ResourceManager.GetString("psOCCURRENCES_CAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Occurrences(%).
        '''</summary>
        Friend Shared ReadOnly Property psOCCURRENCES_PERC_CAP() As String
            Get
                Return ResourceManager.GetString("psOCCURRENCES_PERC_CAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Option.
        '''</summary>
        Friend Shared ReadOnly Property psOPTION_CAP() As String
            Get
                Return ResourceManager.GetString("psOPTION_CAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Options.
        '''</summary>
        Friend Shared ReadOnly Property psOPTIONS() As String
            Get
                Return ResourceManager.GetString("psOPTIONS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Other.
        '''</summary>
        Friend Shared ReadOnly Property psOTHER() As String
            Get
                Return ResourceManager.GetString("psOTHER", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Overall.
        '''</summary>
        Friend Shared ReadOnly Property psOVERALL() As String
            Get
                Return ResourceManager.GetString("psOVERALL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Paint Total 1.
        '''</summary>
        Friend Shared ReadOnly Property psPAINT_TOTAL_CAP() As String
            Get
                Return ResourceManager.GetString("psPAINT_TOTAL_CAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Paint Total 2.
        '''</summary>
        Friend Shared ReadOnly Property psPAINT_TOTAL2_CAP() As String
            Get
                Return ResourceManager.GetString("psPAINT_TOTAL2_CAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Percent.
        '''</summary>
        Friend Shared ReadOnly Property psPERCENT_CAP() As String
            Get
                Return ResourceManager.GetString("psPERCENT_CAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Conveyor Alarms.
        '''</summary>
        Friend Shared ReadOnly Property psPIE_TITLE_CONV() As String
            Get
                Return ResourceManager.GetString("psPIE_TITLE_CONV", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Downtime Alarms by .
        '''</summary>
        Friend Shared ReadOnly Property psPIE_TITLE_DT() As String
            Get
                Return ResourceManager.GetString("psPIE_TITLE_DT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Plant Repair.
        '''</summary>
        Friend Shared ReadOnly Property psPLANT_REPAIR_CAP() As String
            Get
                Return ResourceManager.GetString("psPLANT_REPAIR_CAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Process Name.
        '''</summary>
        Friend Shared ReadOnly Property psPROCESSNAME_CAP() As String
            Get
                Return ResourceManager.GetString("psPROCESSNAME_CAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Production Log Reporting.
        '''</summary>
        Friend Shared ReadOnly Property psPRODUCTION_REPORT() As String
            Get
                Return ResourceManager.GetString("psPRODUCTION_REPORT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Purge Status.
        '''</summary>
        Friend Shared ReadOnly Property psPURGE_STATUS_CAP() As String
            Get
                Return ResourceManager.GetString("psPURGE_STATUS_CAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Failed to find any records of the requested type..
        '''</summary>
        Friend Shared ReadOnly Property psQUERY_FAIL_MSG() As String
            Get
                Return ResourceManager.GetString("psQUERY_FAIL_MSG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ratio.
        '''</summary>
        Friend Shared ReadOnly Property psRATIO_CAP() As String
            Get
                Return ResourceManager.GetString("psRATIO_CAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to RM Charts.
        '''</summary>
        Friend Shared ReadOnly Property psRMCHARTS() As String
            Get
                Return ResourceManager.GetString("psRMCHARTS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Robot Repair.
        '''</summary>
        Friend Shared ReadOnly Property psROBOT_REPAIR_CAP() As String
            Get
                Return ResourceManager.GetString("psROBOT_REPAIR_CAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Records Found.
        '''</summary>
        Friend Shared ReadOnly Property psROWS_FOUND() As String
            Get
                Return ResourceManager.GetString("psROWS_FOUND", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save as CSV(Comma Seperated Value) File.
        '''</summary>
        Friend Shared ReadOnly Property psSAVE_CSV() As String
            Get
                Return ResourceManager.GetString("psSAVE_CSV", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save as XLS(Microsoft Excel) File.
        '''</summary>
        Friend Shared ReadOnly Property psSAVE_XLS() As String
            Get
                Return ResourceManager.GetString("psSAVE_XLS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PAINTworks Reporting.
        '''</summary>
        Friend Shared ReadOnly Property psSCREENCAPTION() As String
            Get
                Return ResourceManager.GetString("psSCREENCAPTION", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Screens.
        '''</summary>
        Friend Shared ReadOnly Property psSCREENS_CAP() As String
            Get
                Return ResourceManager.GetString("psSCREENS_CAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (sec).
        '''</summary>
        Friend Shared ReadOnly Property psSEC() As String
            Get
                Return ResourceManager.GetString("psSEC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select Chart Criteria.
        '''</summary>
        Friend Shared ReadOnly Property psSELECT_CHART() As String
            Get
                Return ResourceManager.GetString("psSELECT_CHART", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select Chart Size.
        '''</summary>
        Friend Shared ReadOnly Property psSELECT_CHART_SIZE() As String
            Get
                Return ResourceManager.GetString("psSELECT_CHART_SIZE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select Chart Type.
        '''</summary>
        Friend Shared ReadOnly Property psSELECT_CHART_TYPE() As String
            Get
                Return ResourceManager.GetString("psSELECT_CHART_TYPE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select Criteria.
        '''</summary>
        Friend Shared ReadOnly Property psSELECT_CRITERIA() As String
            Get
                Return ResourceManager.GetString("psSELECT_CRITERIA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sequence Number.
        '''</summary>
        Friend Shared ReadOnly Property psSEQUENCE_CAP() As String
            Get
                Return ResourceManager.GetString("psSEQUENCE_CAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Severity.
        '''</summary>
        Friend Shared ReadOnly Property psSEVERITY_CAP() As String
            Get
                Return ResourceManager.GetString("psSEVERITY_CAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Set To Shift Times.
        '''</summary>
        Friend Shared ReadOnly Property psSHIFT_BOX_CAP() As String
            Get
                Return ResourceManager.GetString("psSHIFT_BOX_CAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Shift &amp;1.
        '''</summary>
        Friend Shared ReadOnly Property psSHIFT1() As String
            Get
                Return ResourceManager.GetString("psSHIFT1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Shift &amp;2.
        '''</summary>
        Friend Shared ReadOnly Property psSHIFT2() As String
            Get
                Return ResourceManager.GetString("psSHIFT2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Shift &amp;3.
        '''</summary>
        Friend Shared ReadOnly Property psSHIFT3() As String
            Get
                Return ResourceManager.GetString("psSHIFT3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to One Alarm .
        '''</summary>
        Friend Shared ReadOnly Property psSINGLE_ALARM() As String
            Get
                Return ResourceManager.GetString("psSINGLE_ALARM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Start.
        '''</summary>
        Friend Shared ReadOnly Property psSTART() As String
            Get
                Return ResourceManager.GetString("psSTART", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Start Time.
        '''</summary>
        Friend Shared ReadOnly Property psSTART_TIME_CAP() As String
            Get
                Return ResourceManager.GetString("psSTART_TIME_CAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Style.
        '''</summary>
        Friend Shared ReadOnly Property psSTYLE_CAP() As String
            Get
                Return ResourceManager.GetString("psSTYLE_CAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Summary by .
        '''</summary>
        Friend Shared ReadOnly Property psSUMMARY_BY() As String
            Get
                Return ResourceManager.GetString("psSUMMARY_BY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Summary Report.
        '''</summary>
        Friend Shared ReadOnly Property psSUMMARY_REPORT() As String
            Get
                Return ResourceManager.GetString("psSUMMARY_REPORT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Categories Found.
        '''</summary>
        Friend Shared ReadOnly Property psSUMMARY_ROWS_FOUND() As String
            Get
                Return ResourceManager.GetString("psSUMMARY_ROWS_FOUND", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This Week.
        '''</summary>
        Friend Shared ReadOnly Property psTHIS_WEEK() As String
            Get
                Return ResourceManager.GetString("psTHIS_WEEK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Current Week&apos;s.
        '''</summary>
        Friend Shared ReadOnly Property psTHIS_WEEK_TITLE_PRE() As String
            Get
                Return ResourceManager.GetString("psTHIS_WEEK_TITLE_PRE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ThisWeek.
        '''</summary>
        Friend Shared ReadOnly Property psTHISWEEK() As String
            Get
                Return ResourceManager.GetString("psTHISWEEK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to To.
        '''</summary>
        Friend Shared ReadOnly Property psTO() As String
            Get
                Return ResourceManager.GetString("psTO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Top .
        '''</summary>
        Friend Shared ReadOnly Property psTOP_X() As String
            Get
                Return ResourceManager.GetString("psTOP_X", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Total of Each Week&apos;s .
        '''</summary>
        Friend Shared ReadOnly Property psTOT_EACH_WEEK() As String
            Get
                Return ResourceManager.GetString("psTOT_EACH_WEEK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Total.
        '''</summary>
        Friend Shared ReadOnly Property psTOTAL_CAP() As String
            Get
                Return ResourceManager.GetString("psTOTAL_CAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to TuTone.
        '''</summary>
        Friend Shared ReadOnly Property psTUTONE_CAP() As String
            Get
                Return ResourceManager.GetString("psTUTONE_CAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unknown.
        '''</summary>
        Friend Shared ReadOnly Property psUNKNOWN() As String
            Get
                Return ResourceManager.GetString("psUNKNOWN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unknown Conveyor Status.
        '''</summary>
        Friend Shared ReadOnly Property psUNKNOWN_CONV_STAT() As String
            Get
                Return ResourceManager.GetString("psUNKNOWN_CONV_STAT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Uptime.
        '''</summary>
        Friend Shared ReadOnly Property psUPTIME() As String
            Get
                Return ResourceManager.GetString("psUPTIME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to User Selected.
        '''</summary>
        Friend Shared ReadOnly Property psUSER_SELECTED() As String
            Get
                Return ResourceManager.GetString("psUSER_SELECTED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to VIN Number.
        '''</summary>
        Friend Shared ReadOnly Property psVIN_CAP() As String
            Get
                Return ResourceManager.GetString("psVIN_CAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to week of.
        '''</summary>
        Friend Shared ReadOnly Property psWEEK_OF() As String
            Get
                Return ResourceManager.GetString("psWEEK_OF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Weekly Report.
        '''</summary>
        Friend Shared ReadOnly Property psWEEKLY_REPORT() As String
            Get
                Return ResourceManager.GetString("psWEEKLY_REPORT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to WeeklyReport.
        '''</summary>
        Friend Shared ReadOnly Property psWEEKLY_REPORT_FILENAME() As String
            Get
                Return ResourceManager.GetString("psWEEKLY_REPORT_FILENAME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to YearlyRMData.
        '''</summary>
        Friend Shared ReadOnly Property psYEARLY_DATA_FILENAME() As String
            Get
                Return ResourceManager.GetString("psYEARLY_DATA_FILENAME", resourceCulture)
            End Get
        End Property
        
        Friend Shared ReadOnly Property reporttype() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("reporttype", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Class
End Namespace
