'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4952
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class ProjectStrings
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("PWBrowser.ProjectStrings", GetType(ProjectStrings).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend Shared ReadOnly Property _Next() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_Next", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property Back() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Back", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property FormIcon() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("FormIcon", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend Shared ReadOnly Property forward() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("forward", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property Previous() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Previous", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Alarm Menu.
        '''</summary>
        Friend Shared ReadOnly Property psALARM_MENU() As String
            Get
                Return ResourceManager.GetString("psALARM_MENU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Applicator Manuals.
        '''</summary>
        Friend Shared ReadOnly Property psAPPLICATOR() As String
            Get
                Return ResourceManager.GetString("psAPPLICATOR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FANUC Applicator Manual.
        '''</summary>
        Friend Shared ReadOnly Property psAPPLICATOR_MANUAL() As String
            Get
                Return ResourceManager.GetString("psAPPLICATOR_MANUAL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Configuration Menu.
        '''</summary>
        Friend Shared ReadOnly Property psCONFIG_MENU() As String
            Get
                Return ResourceManager.GetString("psCONFIG_MENU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Console Log.
        '''</summary>
        Friend Shared ReadOnly Property psCONSLOG() As String
            Get
                Return ResourceManager.GetString("psCONSLOG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Electrical Manuals.
        '''</summary>
        Friend Shared ReadOnly Property psELECTRICAL() As String
            Get
                Return ResourceManager.GetString("psELECTRICAL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to R-30iA P-700iA Flex Controller Documentation.
        '''</summary>
        Friend Shared ReadOnly Property psELECTRICAL_FLEX() As String
            Get
                Return ResourceManager.GetString("psELECTRICAL_FLEX", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to R-30iA Controller (RIA 15.06-1999 Compliant) Documentation.
        '''</summary>
        Friend Shared ReadOnly Property psELECTRICAL_R30iA() As String
            Get
                Return ResourceManager.GetString("psELECTRICAL_R30iA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Equipment Documentation and Procedures.
        '''</summary>
        Friend Shared ReadOnly Property psEQ_DOC() As String
            Get
                Return ResourceManager.GetString("psEQ_DOC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Base and Clear R-30iA Documentation and procedures.
        '''</summary>
        Friend Shared ReadOnly Property psEQ_DOC_R30iA() As String
            Get
                Return ResourceManager.GetString("psEQ_DOC_R30iA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Prime R-J3iB Documentation and procedures.
        '''</summary>
        Friend Shared ReadOnly Property psEQ_DOC_RJ3iB() As String
            Get
                Return ResourceManager.GetString("psEQ_DOC_RJ3iB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error/Diagnostics.
        '''</summary>
        Friend Shared ReadOnly Property psERR_DIAG() As String
            Get
                Return ResourceManager.GetString("psERR_DIAG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Operation Logbook.
        '''</summary>
        Friend Shared ReadOnly Property psLOGBOOK() As String
            Get
                Return ResourceManager.GetString("psLOGBOOK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Macro Log.
        '''</summary>
        Friend Shared ReadOnly Property psMACROLOG() As String
            Get
                Return ResourceManager.GetString("psMACROLOG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Maintenance Menu.
        '''</summary>
        Friend Shared ReadOnly Property psMAINT_MENU() As String
            Get
                Return ResourceManager.GetString("psMAINT_MENU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mechanical Manuals.
        '''</summary>
        Friend Shared ReadOnly Property psMECHANICAL() As String
            Get
                Return ResourceManager.GetString("psMECHANICAL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to R-30iA P-500iA Mechanical Documentation.
        '''</summary>
        Friend Shared ReadOnly Property psMECHANICAL_P500() As String
            Get
                Return ResourceManager.GetString("psMECHANICAL_P500", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to R-30iA P-700iA Flex Mechanical Documentation.
        '''</summary>
        Friend Shared ReadOnly Property psMECHANICAL_P700() As String
            Get
                Return ResourceManager.GetString("psMECHANICAL_P700", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Online Manuals.
        '''</summary>
        Friend Shared ReadOnly Property psONLINE_MANUALS() As String
            Get
                Return ResourceManager.GetString("psONLINE_MANUALS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Operate Menu.
        '''</summary>
        Friend Shared ReadOnly Property psOPERATE_MENU() As String
            Get
                Return ResourceManager.GetString("psOPERATE_MENU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Other Files.
        '''</summary>
        Friend Shared ReadOnly Property psOTHER_FILES() As String
            Get
                Return ResourceManager.GetString("psOTHER_FILES", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PaintTool Documentation and Procedures.
        '''</summary>
        Friend Shared ReadOnly Property psPAINTTOOL_DOC() As String
            Get
                Return ResourceManager.GetString("psPAINTTOOL_DOC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PLC.
        '''</summary>
        Friend Shared ReadOnly Property psPLC() As String
            Get
                Return ResourceManager.GetString("psPLC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PLC Rack 2.
        '''</summary>
        Friend Shared ReadOnly Property psPLC_RACK2() As String
            Get
                Return ResourceManager.GetString("psPLC_RACK2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PLC Rack 3.
        '''</summary>
        Friend Shared ReadOnly Property psPLC_RACK3() As String
            Get
                Return ResourceManager.GetString("psPLC_RACK3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PLC Rack 4.
        '''</summary>
        Friend Shared ReadOnly Property psPLC_RACK4() As String
            Get
                Return ResourceManager.GetString("psPLC_RACK4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Process Menu.
        '''</summary>
        Friend Shared ReadOnly Property psPROCESS_MENU() As String
            Get
                Return ResourceManager.GetString("psPROCESS_MENU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PAINTworks Online Help.
        '''</summary>
        Friend Shared ReadOnly Property psPWHELP() As String
            Get
                Return ResourceManager.GetString("psPWHELP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reports Menu.
        '''</summary>
        Friend Shared ReadOnly Property psREPORTS_MENU() As String
            Get
                Return ResourceManager.GetString("psREPORTS_MENU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to V6.40 R-J3iB Paint and Dispense Documentation.
        '''</summary>
        Friend Shared ReadOnly Property psRJ3iB_640() As String
            Get
                Return ResourceManager.GetString("psRJ3iB_640", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PAINTworks Browser.
        '''</summary>
        Friend Shared ReadOnly Property psSCREENCAPTION() As String
            Get
                Return ResourceManager.GetString("psSCREENCAPTION", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select page to view..
        '''</summary>
        Friend Shared ReadOnly Property psSELECT_PAGE() As String
            Get
                Return ResourceManager.GetString("psSELECT_PAGE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sofware Manuals.
        '''</summary>
        Friend Shared ReadOnly Property psSOFTWARE() As String
            Get
                Return ResourceManager.GetString("psSOFTWARE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to V7.50 PaintTool (R-30iA) Documentation.
        '''</summary>
        Friend Shared ReadOnly Property psSOFTWARE_R30iA() As String
            Get
                Return ResourceManager.GetString("psSOFTWARE_R30iA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Status Summary.
        '''</summary>
        Friend Shared ReadOnly Property psSUMMARY() As String
            Get
                Return ResourceManager.GetString("psSUMMARY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Switch.
        '''</summary>
        Friend Shared ReadOnly Property psSWITCH() As String
            Get
                Return ResourceManager.GetString("psSWITCH", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to TP files.
        '''</summary>
        Friend Shared ReadOnly Property psTP_FILES() As String
            Get
                Return ResourceManager.GetString("psTP_FILES", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Utilities Menu.
        '''</summary>
        Friend Shared ReadOnly Property psUTILITIES_MENU() As String
            Get
                Return ResourceManager.GetString("psUTILITIES_MENU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Variable Files.
        '''</summary>
        Friend Shared ReadOnly Property psVARIABLES() As String
            Get
                Return ResourceManager.GetString("psVARIABLES", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Version Status.
        '''</summary>
        Friend Shared ReadOnly Property psVERSION() As String
            Get
                Return ResourceManager.GetString("psVERSION", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to View Menu.
        '''</summary>
        Friend Shared ReadOnly Property psVIEW_MENU() As String
            Get
                Return ResourceManager.GetString("psVIEW_MENU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vision Manuals.
        '''</summary>
        Friend Shared ReadOnly Property psVISION() As String
            Get
                Return ResourceManager.GetString("psVISION", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
