'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5446
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class ProjectStrings
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("DMONSchedMan.ProjectStrings", GetType(ProjectStrings).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend Shared ReadOnly Property DMON() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("DMON", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend Shared ReadOnly Property FormIcon() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("FormIcon", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A:.
        '''</summary>
        Friend Shared ReadOnly Property psA() As String
            Get
                Return ResourceManager.GetString("psA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Act..
        '''</summary>
        Friend Shared ReadOnly Property psACT() As String
            Get
                Return ResourceManager.GetString("psACT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to AI.
        '''</summary>
        Friend Shared ReadOnly Property psAI() As String
            Get
                Return ResourceManager.GetString("psAI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to AI[{0}:{1}].
        '''</summary>
        Friend Shared ReadOnly Property psAI_CMT() As String
            Get
                Return ResourceManager.GetString("psAI_CMT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to AO.
        '''</summary>
        Friend Shared ReadOnly Property psAO() As String
            Get
                Return ResourceManager.GetString("psAO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to AO[{0}:{1}].
        '''</summary>
        Friend Shared ReadOnly Property psAO_CMT() As String
            Get
                Return ResourceManager.GetString("psAO_CMT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Archive Zips.
        '''</summary>
        Friend Shared ReadOnly Property psARCHIVE() As String
            Get
                Return ResourceManager.GetString("psARCHIVE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Axis.
        '''</summary>
        Friend Shared ReadOnly Property psAXIS() As String
            Get
                Return ResourceManager.GetString("psAXIS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Axis.
        '''</summary>
        Friend Shared ReadOnly Property psAXIS_TAB() As String
            Get
                Return ResourceManager.GetString("psAXIS_TAB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Browse.
        '''</summary>
        Friend Shared ReadOnly Property psBROWSE() As String
            Get
                Return ResourceManager.GetString("psBROWSE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error accessing axis configuration..
        '''</summary>
        Friend Shared ReadOnly Property psBROWSE_AXIS_ERR() As String
            Get
                Return ResourceManager.GetString("psBROWSE_AXIS_ERR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Browse for item configuration..
        '''</summary>
        Friend Shared ReadOnly Property psBROWSE_CAP() As String
            Get
                Return ResourceManager.GetString("psBROWSE_CAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error accessing register configuration..
        '''</summary>
        Friend Shared ReadOnly Property psBROWSE_REG_ERR() As String
            Get
                Return ResourceManager.GetString("psBROWSE_REG_ERR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Comment.
        '''</summary>
        Friend Shared ReadOnly Property psCOMMENT() As String
            Get
                Return ResourceManager.GetString("psCOMMENT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Name.
        '''</summary>
        Friend Shared ReadOnly Property psCONTROLLER_NAME() As String
            Get
                Return ResourceManager.GetString("psCONTROLLER_NAME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Days To Keep.
        '''</summary>
        Friend Shared ReadOnly Property psDAYS_TO_KEEP() As String
            Get
                Return ResourceManager.GetString("psDAYS_TO_KEEP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Default {0} for {1} not found.  Browse for file?.
        '''</summary>
        Friend Shared ReadOnly Property psDEFAULT_NOT_FOUND() As String
            Get
                Return ResourceManager.GetString("psDEFAULT_NOT_FOUND", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Default Not Found..
        '''</summary>
        Friend Shared ReadOnly Property psDEFAULT_NOT_FOUND_CAP() As String
            Get
                Return ResourceManager.GetString("psDEFAULT_NOT_FOUND_CAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Description.
        '''</summary>
        Friend Shared ReadOnly Property psDESC() As String
            Get
                Return ResourceManager.GetString("psDESC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DI.
        '''</summary>
        Friend Shared ReadOnly Property psDI() As String
            Get
                Return ResourceManager.GetString("psDI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DI[{0}:{1}].
        '''</summary>
        Friend Shared ReadOnly Property psDI_CMT() As String
            Get
                Return ResourceManager.GetString("psDI_CMT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Disabled.
        '''</summary>
        Friend Shared ReadOnly Property psDISABLED() As String
            Get
                Return ResourceManager.GetString("psDISABLED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DMON .
        '''</summary>
        Friend Shared ReadOnly Property psDMON() As String
            Get
                Return ResourceManager.GetString("psDMON", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DMON Auto Sample.
        '''</summary>
        Friend Shared ReadOnly Property psDMON_AUTO_SAMPLE() As String
            Get
                Return ResourceManager.GetString("psDMON_AUTO_SAMPLE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DMON Default {0} {1}.CSV.
        '''</summary>
        Friend Shared ReadOnly Property psDMON_DEFAULTS_FILE() As String
            Get
                Return ResourceManager.GetString("psDMON_DEFAULTS_FILE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DMON Item {0} Axis.
        '''</summary>
        Friend Shared ReadOnly Property psDMON_ITEM_AXIS() As String
            Get
                Return ResourceManager.GetString("psDMON_ITEM_AXIS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DMON Item {0} Description.
        '''</summary>
        Friend Shared ReadOnly Property psDMON_ITEM_DESC() As String
            Get
                Return ResourceManager.GetString("psDMON_ITEM_DESC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DMON Item {0} Group.
        '''</summary>
        Friend Shared ReadOnly Property psDMON_ITEM_GROUP() As String
            Get
                Return ResourceManager.GetString("psDMON_ITEM_GROUP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DMON Item {0} Intercept.
        '''</summary>
        Friend Shared ReadOnly Property psDMON_ITEM_INTERCEPT() As String
            Get
                Return ResourceManager.GetString("psDMON_ITEM_INTERCEPT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DMON Item {0} IO Type.
        '''</summary>
        Friend Shared ReadOnly Property psDMON_ITEM_IO_TYPE() As String
            Get
                Return ResourceManager.GetString("psDMON_ITEM_IO_TYPE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DMON Item {0} Port Number.
        '''</summary>
        Friend Shared ReadOnly Property psDMON_ITEM_PORT_NUM() As String
            Get
                Return ResourceManager.GetString("psDMON_ITEM_PORT_NUM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DMON Item {0} Program Name.
        '''</summary>
        Friend Shared ReadOnly Property psDMON_ITEM_PRG_NAME() As String
            Get
                Return ResourceManager.GetString("psDMON_ITEM_PRG_NAME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DMON Item {0} Slope.
        '''</summary>
        Friend Shared ReadOnly Property psDMON_ITEM_SLOPE() As String
            Get
                Return ResourceManager.GetString("psDMON_ITEM_SLOPE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DMON Item {0} Square.
        '''</summary>
        Friend Shared ReadOnly Property psDMON_ITEM_SQUARE() As String
            Get
                Return ResourceManager.GetString("psDMON_ITEM_SQUARE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DMON Item {0} Type.
        '''</summary>
        Friend Shared ReadOnly Property psDMON_ITEM_TYPE() As String
            Get
                Return ResourceManager.GetString("psDMON_ITEM_TYPE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DMON Item {0} Units.
        '''</summary>
        Friend Shared ReadOnly Property psDMON_ITEM_UNITS() As String
            Get
                Return ResourceManager.GetString("psDMON_ITEM_UNITS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DMON Item {0} Variable Name.
        '''</summary>
        Friend Shared ReadOnly Property psDMON_ITEM_VAR_NAME() As String
            Get
                Return ResourceManager.GetString("psDMON_ITEM_VAR_NAME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DMON PLC Enable.
        '''</summary>
        Friend Shared ReadOnly Property psDMON_PLC_ENABLE() As String
            Get
                Return ResourceManager.GetString("psDMON_PLC_ENABLE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DMON Selected Schedule.
        '''</summary>
        Friend Shared ReadOnly Property psDMON_SCHEDULE() As String
            Get
                Return ResourceManager.GetString("psDMON_SCHEDULE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DMON Schedule {0}  Comment.
        '''</summary>
        Friend Shared ReadOnly Property psDMON_SCHEDULE_COMMENT() As String
            Get
                Return ResourceManager.GetString("psDMON_SCHEDULE_COMMENT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DMON Schedule {0}  Device.
        '''</summary>
        Friend Shared ReadOnly Property psDMON_SCHEDULE_DEVICE() As String
            Get
                Return ResourceManager.GetString("psDMON_SCHEDULE_DEVICE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DMON Schedule {0}  FIle Index.
        '''</summary>
        Friend Shared ReadOnly Property psDMON_SCHEDULE_FILE_INDEX() As String
            Get
                Return ResourceManager.GetString("psDMON_SCHEDULE_FILE_INDEX", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DMON Schedule {0}  File Name.
        '''</summary>
        Friend Shared ReadOnly Property psDMON_SCHEDULE_FILE_NAME() As String
            Get
                Return ResourceManager.GetString("psDMON_SCHEDULE_FILE_NAME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DMON Schedule {0}  File Size (KB).
        '''</summary>
        Friend Shared ReadOnly Property psDMON_SCHEDULE_FILE_SIZE() As String
            Get
                Return ResourceManager.GetString("psDMON_SCHEDULE_FILE_SIZE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DMON Schedule {0}  Item {1}.
        '''</summary>
        Friend Shared ReadOnly Property psDMON_SCHEDULE_ITEM() As String
            Get
                Return ResourceManager.GetString("psDMON_SCHEDULE_ITEM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DMON Schedule {0}  Monitor Frequency Request.
        '''</summary>
        Friend Shared ReadOnly Property psDMON_SCHEDULE_MNTR_REQ() As String
            Get
                Return ResourceManager.GetString("psDMON_SCHEDULE_MNTR_REQ", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DMON Schedule {0}  Number of Items.
        '''</summary>
        Friend Shared ReadOnly Property psDMON_SCHEDULE_NUM_ITEMS() As String
            Get
                Return ResourceManager.GetString("psDMON_SCHEDULE_NUM_ITEMS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DMON Schedule {0}  Record Mode.
        '''</summary>
        Friend Shared ReadOnly Property psDMON_SCHEDULE_REC_MODE() As String
            Get
                Return ResourceManager.GetString("psDMON_SCHEDULE_REC_MODE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DMON Schedule {0}  Record Frequency Request.
        '''</summary>
        Friend Shared ReadOnly Property psDMON_SCHEDULE_REC_REQ() As String
            Get
                Return ResourceManager.GetString("psDMON_SCHEDULE_REC_REQ", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DMON Schedule {0}  Sample Frequency Request.
        '''</summary>
        Friend Shared ReadOnly Property psDMON_SCHEDULE_SAMP_REQ() As String
            Get
                Return ResourceManager.GetString("psDMON_SCHEDULE_SAMP_REQ", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DMON Schedule {0}  Start Condition.
        '''</summary>
        Friend Shared ReadOnly Property psDMON_SCHEDULE_START_COND() As String
            Get
                Return ResourceManager.GetString("psDMON_SCHEDULE_START_COND", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DMON Schedule {0}  Start Enable.
        '''</summary>
        Friend Shared ReadOnly Property psDMON_SCHEDULE_START_ENBL() As String
            Get
                Return ResourceManager.GetString("psDMON_SCHEDULE_START_ENBL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DMON Schedule {0}  Start Item.
        '''</summary>
        Friend Shared ReadOnly Property psDMON_SCHEDULE_START_ITEM() As String
            Get
                Return ResourceManager.GetString("psDMON_SCHEDULE_START_ITEM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DMON Schedule {0}  Start Value.
        '''</summary>
        Friend Shared ReadOnly Property psDMON_SCHEDULE_START_VALUE() As String
            Get
                Return ResourceManager.GetString("psDMON_SCHEDULE_START_VALUE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DMON Schedule {0}  Stop Condition.
        '''</summary>
        Friend Shared ReadOnly Property psDMON_SCHEDULE_STOP_COND() As String
            Get
                Return ResourceManager.GetString("psDMON_SCHEDULE_STOP_COND", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DMON Schedule {0}  Stop Enable.
        '''</summary>
        Friend Shared ReadOnly Property psDMON_SCHEDULE_STOP_ENBL() As String
            Get
                Return ResourceManager.GetString("psDMON_SCHEDULE_STOP_ENBL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DMON Schedule {0}  Stop Item.
        '''</summary>
        Friend Shared ReadOnly Property psDMON_SCHEDULE_STOP_ITEM() As String
            Get
                Return ResourceManager.GetString("psDMON_SCHEDULE_STOP_ITEM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DMON Schedule {0}  Stop Value.
        '''</summary>
        Friend Shared ReadOnly Property psDMON_SCHEDULE_STOP_VALUE() As String
            Get
                Return ResourceManager.GetString("psDMON_SCHEDULE_STOP_VALUE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DMON Files.
        '''</summary>
        Friend Shared ReadOnly Property psDMONFiles() As String
            Get
                Return ResourceManager.GetString("psDMONFiles", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DO.
        '''</summary>
        Friend Shared ReadOnly Property psDO() As String
            Get
                Return ResourceManager.GetString("psDO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DO[{0}:{1}].
        '''</summary>
        Friend Shared ReadOnly Property psDO_CMT() As String
            Get
                Return ResourceManager.GetString("psDO_CMT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Disable auto sample to edit schedules or items..
        '''</summary>
        Friend Shared ReadOnly Property psDSBLAUTOWARN() As String
            Get
                Return ResourceManager.GetString("psDSBLAUTOWARN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enable.
        '''</summary>
        Friend Shared ReadOnly Property psENABLE() As String
            Get
                Return ResourceManager.GetString("psENABLE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to File Device.
        '''</summary>
        Friend Shared ReadOnly Property psFILEDEVICE() As String
            Get
                Return ResourceManager.GetString("psFILEDEVICE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FLPY:.
        '''</summary>
        Friend Shared ReadOnly Property psFILEDEVICE1() As String
            Get
                Return ResourceManager.GetString("psFILEDEVICE1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PRN:.
        '''</summary>
        Friend Shared ReadOnly Property psFILEDEVICE2() As String
            Get
                Return ResourceManager.GetString("psFILEDEVICE2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FR:.
        '''</summary>
        Friend Shared ReadOnly Property psFILEDEVICE3() As String
            Get
                Return ResourceManager.GetString("psFILEDEVICE3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MC:.
        '''</summary>
        Friend Shared ReadOnly Property psFILEDEVICE4() As String
            Get
                Return ResourceManager.GetString("psFILEDEVICE4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CONS:.
        '''</summary>
        Friend Shared ReadOnly Property psFILEDEVICE5() As String
            Get
                Return ResourceManager.GetString("psFILEDEVICE5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to RD:.
        '''</summary>
        Friend Shared ReadOnly Property psFILEDEVICE6() As String
            Get
                Return ResourceManager.GetString("psFILEDEVICE6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to File Index.
        '''</summary>
        Friend Shared ReadOnly Property psFILEINDEX() As String
            Get
                Return ResourceManager.GetString("psFILEINDEX", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to File Name.
        '''</summary>
        Friend Shared ReadOnly Property psFILENAME() As String
            Get
                Return ResourceManager.GetString("psFILENAME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to File Size.
        '''</summary>
        Friend Shared ReadOnly Property psFILESIZE() As String
            Get
                Return ResourceManager.GetString("psFILESIZE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Find.
        '''</summary>
        Friend Shared ReadOnly Property psFIND() As String
            Get
                Return ResourceManager.GetString("psFIND", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Frequency.
        '''</summary>
        Friend Shared ReadOnly Property psFREQUENCY() As String
            Get
                Return ResourceManager.GetString("psFREQUENCY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to G:.
        '''</summary>
        Friend Shared ReadOnly Property psG() As String
            Get
                Return ResourceManager.GetString("psG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to GI.
        '''</summary>
        Friend Shared ReadOnly Property psGI() As String
            Get
                Return ResourceManager.GetString("psGI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to GI[{0}:{1}].
        '''</summary>
        Friend Shared ReadOnly Property psGI_CMT() As String
            Get
                Return ResourceManager.GetString("psGI_CMT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to GO.
        '''</summary>
        Friend Shared ReadOnly Property psGO() As String
            Get
                Return ResourceManager.GetString("psGO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to GO[{0}:{1}].
        '''</summary>
        Friend Shared ReadOnly Property psGO_CMT() As String
            Get
                Return ResourceManager.GetString("psGO_CMT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Import Error.
        '''</summary>
        Friend Shared ReadOnly Property psIMPORT_FAIL_CAP() As String
            Get
                Return ResourceManager.GetString("psIMPORT_FAIL_CAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Import data error = &quot;{0}&quot; on column = &quot;{1}&quot;.  Value = &quot;{2}&quot;.
        '''</summary>
        Friend Shared ReadOnly Property psIMPORT_FAIL_TEXT() As String
            Get
                Return ResourceManager.GetString("psIMPORT_FAIL_TEXT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to There are {0} {1}s available for import..
        '''</summary>
        Friend Shared ReadOnly Property psIMPORT_PROMPT1() As String
            Get
                Return ResourceManager.GetString("psIMPORT_PROMPT1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select &quot;All&quot; or an individual {0} for import.
        '''</summary>
        Friend Shared ReadOnly Property psIMPORT_PROMPT2() As String
            Get
                Return ResourceManager.GetString("psIMPORT_PROMPT2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Import to {0}.
        '''</summary>
        Friend Shared ReadOnly Property psIMPORT_PROMPT3() As String
            Get
                Return ResourceManager.GetString("psIMPORT_PROMPT3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Incomplete selection.  Try again or cancel..
        '''</summary>
        Friend Shared ReadOnly Property psINC_SEL() As String
            Get
                Return ResourceManager.GetString("psINC_SEL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Incomplete Selection..
        '''</summary>
        Friend Shared ReadOnly Property psINC_SEL_CAP() As String
            Get
                Return ResourceManager.GetString("psINC_SEL_CAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Integer.
        '''</summary>
        Friend Shared ReadOnly Property psINTEGER() As String
            Get
                Return ResourceManager.GetString("psINTEGER", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Intercept.
        '''</summary>
        Friend Shared ReadOnly Property psINTERCEPT() As String
            Get
                Return ResourceManager.GetString("psINTERCEPT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid variable selection.  Continue selection..
        '''</summary>
        Friend Shared ReadOnly Property psINV_VAR_SEL() As String
            Get
                Return ResourceManager.GetString("psINV_VAR_SEL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid Variable Selection..
        '''</summary>
        Friend Shared ReadOnly Property psINV_VAR_SEL_CAP() As String
            Get
                Return ResourceManager.GetString("psINV_VAR_SEL_CAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to IO.
        '''</summary>
        Friend Shared ReadOnly Property psIO() As String
            Get
                Return ResourceManager.GetString("psIO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to I/O.
        '''</summary>
        Friend Shared ReadOnly Property psIO_TAB() As String
            Get
                Return ResourceManager.GetString("psIO_TAB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to IO Type.
        '''</summary>
        Friend Shared ReadOnly Property psIOTYPE() As String
            Get
                Return ResourceManager.GetString("psIOTYPE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Item.
        '''</summary>
        Friend Shared ReadOnly Property psITEM() As String
            Get
                Return ResourceManager.GetString("psITEM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Item {0}.
        '''</summary>
        Friend Shared ReadOnly Property psITEM_X() As String
            Get
                Return ResourceManager.GetString("psITEM_X", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Items.
        '''</summary>
        Friend Shared ReadOnly Property psITEMS() As String
            Get
                Return ResourceManager.GetString("psITEMS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Job or CC.
        '''</summary>
        Friend Shared ReadOnly Property psJOBORCC() As String
            Get
                Return ResourceManager.GetString("psJOBORCC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to KB.
        '''</summary>
        Friend Shared ReadOnly Property psKB() As String
            Get
                Return ResourceManager.GetString("psKB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Monitor.
        '''</summary>
        Friend Shared ReadOnly Property psMONITOR() As String
            Get
                Return ResourceManager.GetString("psMONITOR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Number of Items.
        '''</summary>
        Friend Shared ReadOnly Property psNUMITEMS() As String
            Get
                Return ResourceManager.GetString("psNUMITEMS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Port or Register Number.
        '''</summary>
        Friend Shared ReadOnly Property psPORTNUM() As String
            Get
                Return ResourceManager.GetString("psPORTNUM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Program Name.
        '''</summary>
        Friend Shared ReadOnly Property psPRGNAME() As String
            Get
                Return ResourceManager.GetString("psPRGNAME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Print All.
        '''</summary>
        Friend Shared ReadOnly Property psPRINTALL() As String
            Get
                Return ResourceManager.GetString("psPRINTALL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Program selected.  Continue selection.
        '''</summary>
        Friend Shared ReadOnly Property psPROG_SEL() As String
            Get
                Return ResourceManager.GetString("psPROG_SEL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Real.
        '''</summary>
        Friend Shared ReadOnly Property psREAL() As String
            Get
                Return ResourceManager.GetString("psREAL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Record.
        '''</summary>
        Friend Shared ReadOnly Property psRECORD() As String
            Get
                Return ResourceManager.GetString("psRECORD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Record Mode.
        '''</summary>
        Friend Shared ReadOnly Property psRECORDMODE() As String
            Get
                Return ResourceManager.GetString("psRECORDMODE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to One Buffer.
        '''</summary>
        Friend Shared ReadOnly Property psRECORDMODE1() As String
            Get
                Return ResourceManager.GetString("psRECORDMODE1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Continuous.
        '''</summary>
        Friend Shared ReadOnly Property psRECORDMODE2() As String
            Get
                Return ResourceManager.GetString("psRECORDMODE2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to R[{0}:{1}].
        '''</summary>
        Friend Shared ReadOnly Property psREG_CMT() As String
            Get
                Return ResourceManager.GetString("psREG_CMT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Registers.
        '''</summary>
        Friend Shared ReadOnly Property psREG_TAB() As String
            Get
                Return ResourceManager.GetString("psREG_TAB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Register.
        '''</summary>
        Friend Shared ReadOnly Property psREGISTER() As String
            Get
                Return ResourceManager.GetString("psREGISTER", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Req..
        '''</summary>
        Friend Shared ReadOnly Property psREQ() As String
            Get
                Return ResourceManager.GetString("psREQ", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Restore Defaults.
        '''</summary>
        Friend Shared ReadOnly Property psRESTORE_DEFAULT_MNU() As String
            Get
                Return ResourceManager.GetString("psRESTORE_DEFAULT_MNU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to RI.
        '''</summary>
        Friend Shared ReadOnly Property psRI() As String
            Get
                Return ResourceManager.GetString("psRI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to RI[{0}:{1}].
        '''</summary>
        Friend Shared ReadOnly Property psRI_CMT() As String
            Get
                Return ResourceManager.GetString("psRI_CMT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to RO.
        '''</summary>
        Friend Shared ReadOnly Property psRO() As String
            Get
                Return ResourceManager.GetString("psRO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to RO[{0}:{1}].
        '''</summary>
        Friend Shared ReadOnly Property psRO_CMT() As String
            Get
                Return ResourceManager.GetString("psRO_CMT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sample.
        '''</summary>
        Friend Shared ReadOnly Property psSAMPLE() As String
            Get
                Return ResourceManager.GetString("psSAMPLE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save current data as default {0} for {1} to {2}?.
        '''</summary>
        Friend Shared ReadOnly Property psSAVE_DEFAULT() As String
            Get
                Return ResourceManager.GetString("psSAVE_DEFAULT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save Default {0} for {1}.
        '''</summary>
        Friend Shared ReadOnly Property psSAVE_DEFAULT_CAP() As String
            Get
                Return ResourceManager.GetString("psSAVE_DEFAULT_CAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save Defaults.
        '''</summary>
        Friend Shared ReadOnly Property psSAVE_DEFAULT_MNU() As String
            Get
                Return ResourceManager.GetString("psSAVE_DEFAULT_MNU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} already exists.  Overwrite with new default {1} for {2}?.
        '''</summary>
        Friend Shared ReadOnly Property psSAVE_DEFAULT_OW() As String
            Get
                Return ResourceManager.GetString("psSAVE_DEFAULT_OW", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Schedule.
        '''</summary>
        Friend Shared ReadOnly Property psSCHEDULE() As String
            Get
                Return ResourceManager.GetString("psSCHEDULE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Schedules.
        '''</summary>
        Friend Shared ReadOnly Property psSCHEDULES() As String
            Get
                Return ResourceManager.GetString("psSCHEDULES", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DMONSchedMan.
        '''</summary>
        Friend Shared ReadOnly Property psSCREENCAPTION() As String
            Get
                Return ResourceManager.GetString("psSCREENCAPTION", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Slope.
        '''</summary>
        Friend Shared ReadOnly Property psSLOPE() As String
            Get
                Return ResourceManager.GetString("psSLOPE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Start Item.
        '''</summary>
        Friend Shared ReadOnly Property psSTARTITEM() As String
            Get
                Return ResourceManager.GetString("psSTARTITEM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to =.
        '''</summary>
        Friend Shared ReadOnly Property psSTARTSTOPCOND1() As String
            Get
                Return ResourceManager.GetString("psSTARTSTOPCOND1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;&gt;.
        '''</summary>
        Friend Shared ReadOnly Property psSTARTSTOPCOND2() As String
            Get
                Return ResourceManager.GetString("psSTARTSTOPCOND2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;.
        '''</summary>
        Friend Shared ReadOnly Property psSTARTSTOPCOND3() As String
            Get
                Return ResourceManager.GetString("psSTARTSTOPCOND3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;=.
        '''</summary>
        Friend Shared ReadOnly Property psSTARTSTOPCOND4() As String
            Get
                Return ResourceManager.GetString("psSTARTSTOPCOND4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &gt;.
        '''</summary>
        Friend Shared ReadOnly Property psSTARTSTOPCOND5() As String
            Get
                Return ResourceManager.GetString("psSTARTSTOPCOND5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &gt;=.
        '''</summary>
        Friend Shared ReadOnly Property psSTARTSTOPCOND6() As String
            Get
                Return ResourceManager.GetString("psSTARTSTOPCOND6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stop Item.
        '''</summary>
        Friend Shared ReadOnly Property psSTOPITEM() As String
            Get
                Return ResourceManager.GetString("psSTOPITEM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to System.
        '''</summary>
        Friend Shared ReadOnly Property psSYSTEM() As String
            Get
                Return ResourceManager.GetString("psSYSTEM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Type.
        '''</summary>
        Friend Shared ReadOnly Property psTYPE() As String
            Get
                Return ResourceManager.GetString("psTYPE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Units.
        '''</summary>
        Friend Shared ReadOnly Property psUNITS() As String
            Get
                Return ResourceManager.GetString("psUNITS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unknown.
        '''</summary>
        Friend Shared ReadOnly Property psUNKNOWN() As String
            Get
                Return ResourceManager.GetString("psUNKNOWN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Axis {0} is not valid.  Group {1}  has {2} axes..
        '''</summary>
        Friend Shared ReadOnly Property psVAL_AXIS_AXIS_ERR() As String
            Get
                Return ResourceManager.GetString("psVAL_AXIS_AXIS_ERR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Axis {0} is not valid.  Group {1}  has 1 axis..
        '''</summary>
        Friend Shared ReadOnly Property psVAL_AXIS_AXIS_ERR1() As String
            Get
                Return ResourceManager.GetString("psVAL_AXIS_AXIS_ERR1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Group {0} is not valid.  This controller has {1} motion groups..
        '''</summary>
        Friend Shared ReadOnly Property psVAL_AXIS_GROUP_ERR() As String
            Get
                Return ResourceManager.GetString("psVAL_AXIS_GROUP_ERR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Group {0} is not valid.  This controller has 1 motion group..
        '''</summary>
        Friend Shared ReadOnly Property psVAL_AXIS_GROUP_ERR1() As String
            Get
                Return ResourceManager.GetString("psVAL_AXIS_GROUP_ERR1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Axis validation error: .
        '''</summary>
        Friend Shared ReadOnly Property psVAL_AXIS_VAL_ERR() As String
            Get
                Return ResourceManager.GetString("psVAL_AXIS_VAL_ERR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Item Validation.
        '''</summary>
        Friend Shared ReadOnly Property psVAL_CAP() As String
            Get
                Return ResourceManager.GetString("psVAL_CAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Item Validation Error: .
        '''</summary>
        Friend Shared ReadOnly Property psVAL_ERR1() As String
            Get
                Return ResourceManager.GetString("psVAL_ERR1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Variable Validation Error: .
        '''</summary>
        Friend Shared ReadOnly Property psVAL_ERR2() As String
            Get
                Return ResourceManager.GetString("psVAL_ERR2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Item setup incomplete.
        '''</summary>
        Friend Shared ReadOnly Property psVAL_IMCOMP() As String
            Get
                Return ResourceManager.GetString("psVAL_IMCOMP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0}[{1}] not found..
        '''</summary>
        Friend Shared ReadOnly Property psVAL_IO_POINT_NOT_FOUND() As String
            Get
                Return ResourceManager.GetString("psVAL_IO_POINT_NOT_FOUND", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to I/O type not found..
        '''</summary>
        Friend Shared ReadOnly Property psVAL_IO_TYPE_NOT_FOUND() As String
            Get
                Return ResourceManager.GetString("psVAL_IO_TYPE_NOT_FOUND", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to I/O type validation error: .
        '''</summary>
        Friend Shared ReadOnly Property psVAL_IO_TYPE_VAL_ERR() As String
            Get
                Return ResourceManager.GetString("psVAL_IO_TYPE_VAL_ERR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Validation successful..
        '''</summary>
        Friend Shared ReadOnly Property psVAL_OK() As String
            Get
                Return ResourceManager.GetString("psVAL_OK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Karel Variable &quot;{0}&quot; not found..
        '''</summary>
        Friend Shared ReadOnly Property psVAL_PRG_NOT_FOUND() As String
            Get
                Return ResourceManager.GetString("psVAL_PRG_NOT_FOUND", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Karel Variable &quot;[{0}]{1}&quot; not found..
        '''</summary>
        Friend Shared ReadOnly Property psVAL_PRG_VAR_NOT_FOUND() As String
            Get
                Return ResourceManager.GetString("psVAL_PRG_VAR_NOT_FOUND", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Karel Variable &quot;[{0}]{1}&quot; is an array or a structure, not an individual variable.  .
        '''</summary>
        Friend Shared ReadOnly Property psVAL_PRG_VAR_STRUCTURE() As String
            Get
                Return ResourceManager.GetString("psVAL_PRG_VAR_STRUCTURE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Register validation error..
        '''</summary>
        Friend Shared ReadOnly Property psVAL_REG_ERR() As String
            Get
                Return ResourceManager.GetString("psVAL_REG_ERR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Register {0} not found..
        '''</summary>
        Friend Shared ReadOnly Property psVAL_REG_NOT_FOUND() As String
            Get
                Return ResourceManager.GetString("psVAL_REG_NOT_FOUND", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to System Variable &quot;{0}&quot; not found..
        '''</summary>
        Friend Shared ReadOnly Property psVAL_SYS_VAR_NOT_FOUND() As String
            Get
                Return ResourceManager.GetString("psVAL_SYS_VAR_NOT_FOUND", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to System Variable &quot;{0}&quot;  is an array or a structure, not an individual variable..
        '''</summary>
        Friend Shared ReadOnly Property psVAL_SYS_VAR_STRUCTURE() As String
            Get
                Return ResourceManager.GetString("psVAL_SYS_VAR_STRUCTURE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Variable type mismatch.  Type on controller is {0}..
        '''</summary>
        Friend Shared ReadOnly Property psVAL_VAR_TYPE_MISMATCH() As String
            Get
                Return ResourceManager.GetString("psVAL_VAR_TYPE_MISMATCH", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Import Data Not Found..
        '''</summary>
        Friend Shared ReadOnly Property psVALID_IMPORT_DATA_NOT_FOUND_CAP() As String
            Get
                Return ResourceManager.GetString("psVALID_IMPORT_DATA_NOT_FOUND_CAP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The selected file does not contain valid data for import.
        '''</summary>
        Friend Shared ReadOnly Property psVALID_IMPORT_DATA_NOT_FOUND_TEXT() As String
            Get
                Return ResourceManager.GetString("psVALID_IMPORT_DATA_NOT_FOUND_TEXT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Validate.
        '''</summary>
        Friend Shared ReadOnly Property psVALIDATE() As String
            Get
                Return ResourceManager.GetString("psVALIDATE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Variables.
        '''</summary>
        Friend Shared ReadOnly Property psVAR_TAB() As String
            Get
                Return ResourceManager.GetString("psVAR_TAB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} variable selected.  Not valid for DMON..
        '''</summary>
        Friend Shared ReadOnly Property psVAR_TYPE_SEL_NOK() As String
            Get
                Return ResourceManager.GetString("psVAR_TYPE_SEL_NOK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} variable selected.  Valid for DMON..
        '''</summary>
        Friend Shared ReadOnly Property psVAR_TYPE_SEL_OK() As String
            Get
                Return ResourceManager.GetString("psVAR_TYPE_SEL_OK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Variable Name.
        '''</summary>
        Friend Shared ReadOnly Property psVARNAME() As String
            Get
                Return ResourceManager.GetString("psVARNAME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Structure or Array selected.  Continue selection.
        '''</summary>
        Friend Shared ReadOnly Property psVARS_SEL() As String
            Get
                Return ResourceManager.GetString("psVARS_SEL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to WI.
        '''</summary>
        Friend Shared ReadOnly Property psWI() As String
            Get
                Return ResourceManager.GetString("psWI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to WO.
        '''</summary>
        Friend Shared ReadOnly Property psWO() As String
            Get
                Return ResourceManager.GetString("psWO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to WO[{0}:{1}].
        '''</summary>
        Friend Shared ReadOnly Property psWO_CMT() As String
            Get
                Return ResourceManager.GetString("psWO_CMT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to WI[{0}:{1}].
        '''</summary>
        Friend Shared ReadOnly Property pWI_CMT() As String
            Get
                Return ResourceManager.GetString("pWI_CMT", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
