'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3615
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class ProjectStrings
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Clock.ProjectStrings", GetType(ProjectStrings).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend Shared ReadOnly Property FormIcon() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("FormIcon", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Copy GUI Time/Date to All Devices.
        '''</summary>
        Friend Shared ReadOnly Property psCOPY_GUI_TIME_TO_ALL() As String
            Get
                Return ResourceManager.GetString("psCOPY_GUI_TIME_TO_ALL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Copy PLC Time/Date to All Devices.
        '''</summary>
        Friend Shared ReadOnly Property psCOPY_PLC_TIME_TO_ALL() As String
            Get
                Return ResourceManager.GetString("psCOPY_PLC_TIME_TO_ALL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Copy Robot Time/Date to All Devices.
        '''</summary>
        Friend Shared ReadOnly Property psCOPY_ROBOT_TIME_TO_ALL() As String
            Get
                Return ResourceManager.GetString("psCOPY_ROBOT_TIME_TO_ALL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Date/Time .
        '''</summary>
        Friend Shared ReadOnly Property psDATETIME() As String
            Get
                Return ResourceManager.GetString("psDATETIME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Edit Date.
        '''</summary>
        Friend Shared ReadOnly Property psEDIT_DATE() As String
            Get
                Return ResourceManager.GetString("psEDIT_DATE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Edit Time.
        '''</summary>
        Friend Shared ReadOnly Property psEDIT_TIME() As String
            Get
                Return ResourceManager.GetString("psEDIT_TIME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to GUI Date.
        '''</summary>
        Friend Shared ReadOnly Property psGUI_DATE() As String
            Get
                Return ResourceManager.GetString("psGUI_DATE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to GUI.
        '''</summary>
        Friend Shared ReadOnly Property psGUI_DEVICE_NAME() As String
            Get
                Return ResourceManager.GetString("psGUI_DEVICE_NAME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to GUI Time.
        '''</summary>
        Friend Shared ReadOnly Property psGUI_TIME() As String
            Get
                Return ResourceManager.GetString("psGUI_TIME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PLC Date.
        '''</summary>
        Friend Shared ReadOnly Property psPLC_DATE() As String
            Get
                Return ResourceManager.GetString("psPLC_DATE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PLC.
        '''</summary>
        Friend Shared ReadOnly Property psPLC_DEVICE_NAME() As String
            Get
                Return ResourceManager.GetString("psPLC_DEVICE_NAME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PLC Time.
        '''</summary>
        Friend Shared ReadOnly Property psPLC_TIME() As String
            Get
                Return ResourceManager.GetString("psPLC_TIME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Robot .
        '''</summary>
        Friend Shared ReadOnly Property psROBOT() As String
            Get
                Return ResourceManager.GetString("psROBOT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Robot Controllers.
        '''</summary>
        Friend Shared ReadOnly Property psROBOT_CONTROLLERS() As String
            Get
                Return ResourceManager.GetString("psROBOT_CONTROLLERS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Date.
        '''</summary>
        Friend Shared ReadOnly Property psROBOT_DATE() As String
            Get
                Return ResourceManager.GetString("psROBOT_DATE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Name.
        '''</summary>
        Friend Shared ReadOnly Property psROBOT_NAME() As String
            Get
                Return ResourceManager.GetString("psROBOT_NAME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Time.
        '''</summary>
        Friend Shared ReadOnly Property psROBOT_TIME() As String
            Get
                Return ResourceManager.GetString("psROBOT_TIME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Clock.
        '''</summary>
        Friend Shared ReadOnly Property psSCREENCAPTION() As String
            Get
                Return ResourceManager.GetString("psSCREENCAPTION", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
